import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../presentation/providers/auth_provider.dart';

final localizationProvider = Provider<AppLocalizations>((ref) {
  final langCode = ref.watch(authProvider).user?.language ?? 'es';
  return AppLocalizations(langCode);
});

class AppLocalizations {
  final String langCode;

  AppLocalizations(this.langCode);

  String get intlLocale {
    final lower = langCode.toLowerCase();
    if (lower == 'español' || lower == 'es') return 'es';
    if (lower == 'english' || lower == 'en') return 'en';
    if (lower == 'português' || lower == 'pt') return 'pt';
    if (lower == 'français' || lower == 'fr') return 'fr';
    if (lower == 'italiano' || lower == 'it') return 'it';
    return 'es'; // default fallback
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'es': {
      'settings_title': 'Configuración ⚙️',
      'settings_subtitle': 'Personaliza tu experiencia',
      'edit_profile': 'Editar Perfil',
      'premium_upgrade': 'Actualizar a Premium',
      'premium_desc': 'Desbloquea todas las funciones: sin anuncios, reportes avanzados, sincronización en la nube y más.',
      'see_plans': 'Ver Planes',
      'general': 'General',
      'notifications': 'Notificaciones',
      'notifications_desc': 'Alertas y recordatorios',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'dark_theme_desc': 'Activar modo nocturno',
      'security': 'Seguridad',
      'change_password': 'Cambiar Contraseña',
      'change_password_desc': 'Última actualización hace 3 meses',
      'two_factor': 'Autenticación de Dos Factores',
      'two_factor_desc': 'Protege tu cuenta',
      'budgets': 'Presupuestos',
      'category_budget': 'Presupuesto por Categoría',
      'category_budget_desc': 'Establece límites por rubro',
      'budget_alerts': 'Alertas de Presupuesto',
      'budget_alerts_desc': 'Notificaciones al acercarte al límite',
      'appearance': 'Apariencia',
      'color_palette': 'Paleta de Colores',
      'color_palette_desc': 'Personaliza tus colores',
      'data': 'Datos',
      'cloud_sync': 'Sincronización en la Nube',
      'cloud_sync_desc': 'Premium',
      'local_backup': 'Respaldo Local',
      'local_backup_desc': 'Último respaldo: Hoy',
      'export_data': 'Exportar Datos',
      'export_data_desc': 'Descargar en formato CSV',
      'logout': 'Cerrar Sesión',
      'currency': 'Moneda',
      'currency_desc': 'Selecciona tu moneda local',
      'dashboard': 'Dashboard',
      'transactions': 'Transacciones',
      'expenses': 'Gastos',
      'total_balance': 'Balance Total',
      'income': 'Ingresos',
      'total_expenses': 'Gastos Totales',
      'recent_transactions': 'Transacciones Recientes',
      'see_all': 'Ver todas',
      'select_language': 'Seleccionar Idioma',
      'select_language_desc': 'Elige el idioma de la aplicación',
      'select_currency': 'Seleccionar Moneda',
      'select_currency_desc': 'Elige la moneda de la aplicación',
      'select_country': 'Seleccionar País',
      'select_country_desc': 'Elige tu país de residencia',
      
      'complete_profile': '¡Completa tu perfil!',
      'complete_profile_desc': 'Necesitamos algunos datos para personalizar tu experiencia y ayudarte a ahorrar:',
      'country': 'País',
      'salary': 'Salario',
      'complete_now': 'Completar Ahora',
      'fixed_expense': 'Gasto Fijo',
      'new_expense': 'Nuevo Gasto',
      'amount': 'Monto',
      'category': 'Categoría',
      'description_optional': 'Descripción (Opcional)',
      'date': 'Fecha',
      'add_expense': 'Agregar Gasto',
      'add_fixed_expense': 'Agregar Gasto Fijo',
      'expense_added': 'Gasto agregado exitosamente',
      'fixed_income': 'Ingreso Fijo',
      'new_income': 'Nuevo Ingreso',
      'add_income': 'Agregar Ingreso',
      'income_added': 'Ingreso agregado exitosamente',
      'new_debt': 'Nueva Deuda/Cuota',
      'total_installments': 'Cuotas Totales',
      'paid_installments': 'Cuotas Pagadas',
      'add_debt': 'Agregar Deuda',
      'debt_added': 'Deuda agregada exitosamente',
      'home': 'Inicio',
      'debts': 'Deudas',
      'savings': 'Ahorros',
      'profile': 'Perfil',
      'welcome_back': '¡Hola de nuevo,',
      'your_finances': 'Aquí está tu resumen financiero',
      'add_first_expense': 'Agrega tu primer gasto',
      'add_first_debt': 'Agrega tu primera deuda',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'save_changes': 'Guardar Cambios',
      'careful': '¡Cuidado! ',
      'limit_reached': 'Has alcanzado el ',
      'limit_monthly': '% del límite mensual.',
      'unlocked_badges': 'Insignias Desbloqueadas',
      'quick_actions': 'Acciones Rápidas',
      'income_action': 'Ingreso',
      'expense_action': 'Gasto',
      'ai_assistant': 'Asistente IA',
      'on_track': '¡Increíble! Estás en racha 🔥',
      'my_expenses': 'Mis Gastos 💸',
      'my_incomes': 'Mis Ingresos 💰',
      'my_debts': 'Mis Deudas 💳',
      'my_savings': 'Mis Ahorros 🎯',
      'search_expenses': 'Buscar gastos...',
      'total_expenses_month': 'Total de Gastos -',
      'no_income_yet': 'Sin ingresos registrados aún',
      'expenses_by_category': 'Gastos por Categoría',
      'of_your_income': 'de tus ingresos',
      'voice_ask_payment_method': '¿Este gasto se realizó con Tarjeta de Crédito o en Efectivo?',
      'voice_listening': 'Te estoy escuchando...',
      'voice_tap_to_speak': 'Toca para hablar',
      'voice_help_text': 'Dime tu gasto o ingreso:\n"Gasté 50 en almuerzo"\n"Me pagaron 5000 de salario"',
      'voice_analyzing': 'Analizando tu voz...',
      'voice_confirm_expense': 'Confirmar Gasto',
      'voice_confirm_income': 'Confirmar Ingreso',
      'voice_gasto': 'Gasto',
      'voice_ingreso': 'Ingreso',
      'voice_payment_method': 'Método de pago:',
      'voice_cash': '💵 Efectivo',
      'voice_card': '💳 Tarjeta',
      'voice_select_card': 'Selecciona tu Tarjeta:',
      'voice_no_cards': 'No tienes tarjetas registradas en la app.',
      'voice_try_again': 'Dictar otra vez',
      'voice_save': 'Guardar',
      'voice_success_expense': '¡Gasto registrado!',
      'voice_success_income': '¡Ingreso registrado!',
      'voice_accept': 'Aceptar',
      'voice_no_amount': 'No pude detectar una cantidad válida en: "{text}". Intenta de nuevo diciendo el número.',
      'voice_paying_card_or_cash': '¿Tarjeta o Efectivo?',
      'voice_answer_mic': 'Responde hablando para completar el registro...',
      'dashboard_income': 'Ingresos',
      'dashboard_expenses': 'Gastos',
      'dashboard_debts': 'Deudas',
      'dashboard_cards': 'Tarjetas',
      'badge_pioneer': 'Pionero Antigravity',
      'badge_pioneer_desc': 'Completa tu perfil e identidad',
      'badge_constant_fire': 'Fuego Constante',
      'badge_constant_fire_desc': 'Mantén una racha de 7 días continuos',
      'badge_habit_master': 'Maestro del Hábito',
      'badge_habit_master_desc': '30 días ininterrumpidos en la app',
      'badge_vip_shopper': 'Comprador VIP',
      'badge_vip_shopper_desc': 'Canjea tu primer ítem en la tienda',
      'badge_supreme_collector': 'Coleccionista Supremo',
      'badge_supreme_collector_desc': 'Adquiere 5 ítems o temas exclusivos',
      'badge_financial_mind': 'Mente Financiera',
      'badge_financial_mind_desc': 'Acumula 100 puntos de experiencia',
      'ai_assistant_subtitle': 'Descubre cómo invertir tu dinero basado en tu negocio 💰',
      'what_if_subtitle': 'Simula variaciones en tus ingresos, gastos o deudas y Zent AI predecirá tu salud financiera.',
      'rewards_shop_subtitle': 'Canjea tus puntos ganados',
      'rewards_shop_desc': 'Desbloquea avatares exclusivos, temas personalizados y consejos VIP para potenciar tus finanzas.',
      'rewards_shop_avatars': 'Avatares',
      'rewards_shop_themes': 'Temas',
      'rewards_shop_tips': 'Consejos Pro',
      'rewards_shop_enter': 'Entrar',
      'savings_subtitle': 'Alcanza tus metas financieras',
      'total_saved': 'Total Ahorrado',
      'savings_month_progress': '+12% este mes',
      'savings_guide_plan': 'Plan de Ahorro con Guía',
      'savings_guide_desc': 'Descubre cómo ahorrar más y alcanzar tus metas más rápido',
      'view_guide': 'Ver Guía',
      'add_new_goal': 'Agregar Nueva Meta',
      'my_saving_goals': 'Mis Metas de Ahorro',
      'no_goals_yet': 'Aún no tienes metas de ahorro.',
      'goal_achieved': '¡Logrado!',
      'completed': 'completado',
      'add_funds': 'Agregar fondos',
      'error_loading_savings': 'Error al cargar ahorros',
      'error_loading_goals': 'Error al cargar metas de ahorro',
      'quick_actions_new_goal': 'Nueva Meta de Ahorro',
      'quick_actions_rewards_shop': 'Tienda de Recompensas',
      'quick_actions_footer': 'Selecciona una acción para continuar',
      'quick_actions_new_badge': '{count} nueva(s)',
      'nav_settings': 'Ajustes',
      'what_if_title': 'Simulador "What If?" AI',
      'what_if_tab_controls': 'Controles',
      'what_if_tab_free': 'Escenario Libre',
      'what_if_initial_desc': 'Ajusta los controles de simulación arriba y presiona "Solicitar Diagnóstico a Zent AI" para evaluar tu escenario financiero hipotético.',
      'what_if_chart_title': 'Proyección Flujo de Caja (6 Meses)',
      'what_if_panel_title': 'Panel de Simulación ⚙️',
      'what_if_additional_expense': 'Gasto Mensual Adicional',
      'what_if_income_reduction': 'Reducción de Ingresos',
      'what_if_new_debt_payment': 'Nueva Cuota de Deuda Fija',
      'what_if_request_diagnosis': 'Solicitar Diagnóstico a Zent AI',
      'what_if_diagnosis_title': 'Plan Diagnóstico Zent AI 🧠',
      'what_if_desc_title': '¿Qué pasaría si...?',
      'what_if_desc_subtitle': 'Describe cualquier escenario financiero y la IA analizará cómo afectaría tus finanzas actuales.',
      'what_if_describe_scenario': 'Describe tu escenario',
      'what_if_placeholder': 'Ej: ¿Qué pasaría si me compro una laptop de 10,000 en 6 cuotas? ¿Puedo permitírmelo?',
      'what_if_input_hint': 'Incluye montos, plazos y detalles para un mejor análisis',
      'what_if_analyzing': 'Analizando escenario...',
      'what_if_analyze_btn': 'Analizar Escenario con IA',
      'what_if_analysis_result': 'Análisis de Escenario 🔮',
      'what_if_empty_state': 'Escribe un escenario arriba o selecciona uno de los ejemplos para ver el análisis de la IA',
      'what_if_risk_low': 'Bajo',
      'what_if_risk_moderate': 'Moderado ⚠️',
      'what_if_risk_critical': 'Crítico 🚨',
      'what_if_chip_laptop_title': 'Comprar laptop en cuotas',
      'what_if_chip_laptop_query': '¿Qué pasaría si me compro una laptop de 10000 en 6 cuotas mensuales?',
      'what_if_chip_car_title': 'Comprar carro',
      'what_if_chip_car_query': '¿Qué pasaría si compro un carro de 80000 con un enganche de 20000 y financiamiento a 48 meses?',
      'what_if_chip_salary_title': 'Aumento de salario',
      'what_if_chip_salary_query': '¿Qué pasaría si mi salario aumenta un 20% a partir del próximo mes?',
      'what_if_chip_rent_title': 'Alquilar departamento',
      'what_if_chip_rent_query': '¿Qué pasaría si me mudo a un departamento con renta de 3500 mensuales?',
      'what_if_chip_save_title': 'Ahorrar mensualmente',
      'what_if_chip_save_query': '¿Qué pasaría si empiezo a ahorrar 1500 al mes durante 12 meses?',
      'what_if_chip_phone_title': 'Comprar teléfono',
      'what_if_chip_phone_query': '¿Qué pasaría si me compro un iPhone de 8000 en 12 cuotas?',
      'what_if_chip_masters_title': 'Estudiar maestría',
      'what_if_chip_masters_query': '¿Qué pasaría si empiezo una maestría que cuesta 5000 al mes durante 24 meses?',
      'what_if_chip_job_title': 'Perder empleo',
      'what_if_chip_job_query': '¿Qué pasaría si pierdo mi empleo y me quedo sin ingresos durante 3 meses?',
      'error_analyzing_scenario': 'Error al analizar el escenario',
      'error_obtaining_diagnosis': 'Error al obtener diagnóstico de Zent AI',
    },
    'en': {
      'settings_title': 'Settings ⚙️',
      'settings_subtitle': 'Customize your experience',
      'edit_profile': 'Edit Profile',
      'premium_upgrade': 'Upgrade to Premium',
      'premium_desc': 'Unlock all features: ad-free, advanced reports, cloud sync, and more.',
      'see_plans': 'View Plans',
      'general': 'General',
      'notifications': 'Notifications',
      'notifications_desc': 'Alerts and reminders',
      'language': 'Language',
      'dark_theme': 'Dark Theme',
      'dark_theme_desc': 'Enable night mode',
      'security': 'Security',
      'change_password': 'Change Password',
      'change_password_desc': 'Last updated 3 months ago',
      'two_factor': 'Two-Factor Authentication',
      'two_factor_desc': 'Protect your account',
      'budgets': 'Budgets',
      'category_budget': 'Category Budget',
      'category_budget_desc': 'Set limits by category',
      'budget_alerts': 'Budget Alerts',
      'budget_alerts_desc': 'Notifications when approaching limit',
      'appearance': 'Appearance',
      'color_palette': 'Color Palette',
      'color_palette_desc': 'Customize your colors',
      'data': 'Data',
      'cloud_sync': 'Cloud Sync',
      'cloud_sync_desc': 'Premium',
      'local_backup': 'Local Backup',
      'local_backup_desc': 'Last backup: Today',
      'export_data': 'Export Data',
      'export_data_desc': 'Download as CSV',
      'logout': 'Log Out',
      'currency': 'Currency',
      'currency_desc': 'Select your local currency',
      'dashboard': 'Dashboard',
      'transactions': 'Transactions',
      'expenses': 'Expenses',
      'total_balance': 'Total Balance',
      'income': 'Income',
      'total_expenses': 'Total Expenses',
      'recent_transactions': 'Recent Transactions',
      'see_all': 'See all',
      'select_language': 'Select Language',
      'select_language_desc': 'Choose the application language',
      'select_currency': 'Select Currency',
      'select_currency_desc': 'Choose the application currency',
      'select_country': 'Select Country',
      'select_country_desc': 'Choose your country of residence',
      
      'complete_profile': 'Complete your profile!',
      'complete_profile_desc': 'We need some data to customize your experience and help you save:',
      'country': 'Country',
      'salary': 'Salary',
      'complete_now': 'Complete Now',
      'fixed_expense': 'Fixed Expense',
      'new_expense': 'New Expense',
      'amount': 'Amount',
      'category': 'Category',
      'description_optional': 'Description (Optional)',
      'date': 'Date',
      'add_expense': 'Add Expense',
      'add_fixed_expense': 'Add Fixed Expense',
      'expense_added': 'Expense added successfully',
      'fixed_income': 'Fixed Income',
      'new_income': 'New Income',
      'add_income': 'Add Income',
      'income_added': 'Income added successfully',
      'new_debt': 'New Debt/Installment',
      'total_installments': 'Total Installments',
      'paid_installments': 'Paid Installments',
      'add_debt': 'Add Debt',
      'debt_added': 'Debt added successfully',
      'home': 'Home',
      'debts': 'Debts',
      'savings': 'Savings',
      'profile': 'Profile',
      'welcome_back': 'Welcome back,',
      'your_finances': 'Here is your financial summary',
      'add_first_expense': 'Add your first expense',
      'add_first_debt': 'Add your first debt',
      'save': 'Save',
      'cancel': 'Cancel',
      'save_changes': 'Save Changes',
      'careful': 'Careful! ',
      'limit_reached': 'You have reached ',
      'limit_monthly': '% of your monthly limit.',
      'unlocked_badges': 'Unlocked Badges',
      'quick_actions': 'Quick Actions',
      'income_action': 'Income',
      'expense_action': 'Expense',
      'ai_assistant': 'AI Assistant',
      'on_track': 'Incredible! You are on a streak 🔥',
      'my_expenses': 'My Expenses 💸',
      'my_incomes': 'My Income 💰',
      'my_debts': 'My Debts 💳',
      'my_savings': 'My Savings 🎯',
      'search_expenses': 'Search expenses...',
      'total_expenses_month': 'Total Expenses -',
      'no_income_yet': 'No income registered yet',
      'expenses_by_category': 'Expenses by Category',
      'of_your_income': 'of your income',
      'voice_ask_payment_method': 'Was this expense made with a Credit Card or Cash?',
      'voice_listening': 'I am listening...',
      'voice_tap_to_speak': 'Tap to speak',
      'voice_help_text': 'Tell me your expense or income:\n"I spent 50 on lunch"\n"They paid me 5000 salary"',
      'voice_analyzing': 'Analyzing your voice...',
      'voice_confirm_expense': 'Confirm Expense',
      'voice_confirm_income': 'Confirm Income',
      'voice_gasto': 'Expense',
      'voice_ingreso': 'Income',
      'voice_payment_method': 'Payment method:',
      'voice_cash': '💵 Cash',
      'voice_card': '💳 Card',
      'voice_select_card': 'Select your Card:',
      'voice_no_cards': 'No credit cards registered in the app.',
      'voice_try_again': 'Speak again',
      'voice_save': 'Save',
      'voice_success_expense': 'Expense registered successfully!',
      'voice_success_income': 'Income registered successfully!',
      'voice_accept': 'Accept',
      'voice_no_amount': 'Could not detect a valid amount in: "{text}". Please try again saying the number.',
      'voice_paying_card_or_cash': 'Card or Cash?',
      'voice_answer_mic': 'Answer speaking to complete registration...',
      'dashboard_income': 'Income',
      'dashboard_expenses': 'Expenses',
      'dashboard_debts': 'Debts',
      'dashboard_cards': 'Cards',
      'badge_pioneer': 'Antigravity Pioneer',
      'badge_pioneer_desc': 'Complete your profile and identity',
      'badge_constant_fire': 'Constant Fire',
      'badge_constant_fire_desc': 'Keep a streak of 7 continuous days',
      'badge_habit_master': 'Habit Master',
      'badge_habit_master_desc': '30 uninterrupted days in the app',
      'badge_vip_shopper': 'VIP Shopper',
      'badge_vip_shopper_desc': 'Redeem your first item in the shop',
      'badge_supreme_collector': 'Supreme Collector',
      'badge_supreme_collector_desc': 'Acquire 5 exclusive items or themes',
      'badge_financial_mind': 'Financial Mind',
      'badge_financial_mind_desc': 'Accumulate 100 experience points',
      'ai_assistant_subtitle': 'Discover how to invest your money based on your business 💰',
      'what_if_subtitle': 'Simulate variations in your income, expenses or debts and Zent AI will predict your financial health.',
      'rewards_shop_subtitle': 'Redeem your earned points',
      'rewards_shop_desc': 'Unlock exclusive avatars, custom themes and VIP tips to boost your finances.',
      'rewards_shop_avatars': 'Avatars',
      'rewards_shop_themes': 'Themes',
      'rewards_shop_tips': 'Pro Tips',
      'rewards_shop_enter': 'Enter',
      'savings_subtitle': 'Reach your financial goals',
      'total_saved': 'Total Saved',
      'savings_month_progress': '+12% this month',
      'savings_guide_plan': 'Guided Savings Plan',
      'savings_guide_desc': 'Discover how to save more and reach your goals faster',
      'view_guide': 'View Guide',
      'add_new_goal': 'Add New Goal',
      'my_saving_goals': 'My Saving Goals',
      'no_goals_yet': 'You don\'t have saving goals yet.',
      'goal_achieved': 'Achieved!',
      'completed': 'completed',
      'add_funds': 'Add funds',
      'error_loading_savings': 'Error loading savings',
      'error_loading_goals': 'Error loading saving goals',
      'quick_actions_new_goal': 'New Saving Goal',
      'quick_actions_rewards_shop': 'Rewards Shop',
      'quick_actions_footer': 'Select an action to continue',
      'quick_actions_new_badge': '{count} new',
      'nav_settings': 'Settings',
      'what_if_title': 'AI "What If?" Simulator',
      'what_if_tab_controls': 'Controls',
      'what_if_tab_free': 'Free Scenario',
      'what_if_initial_desc': 'Adjust the simulation controls above and press "Request Diagnosis from Zent AI" to evaluate your hypothetical financial scenario.',
      'what_if_chart_title': 'Cash Flow Projection (6 Months)',
      'what_if_panel_title': 'Simulation Panel ⚙️',
      'what_if_additional_expense': 'Additional Monthly Expense',
      'what_if_income_reduction': 'Income Reduction',
      'what_if_new_debt_payment': 'New Fixed Debt Installment',
      'what_if_request_diagnosis': 'Request Diagnosis from Zent AI',
      'what_if_diagnosis_title': 'Zent AI Diagnosis Plan 🧠',
      'what_if_desc_title': 'What would happen if...?',
      'what_if_desc_subtitle': 'Describe any financial scenario and the AI will analyze how it would affect your current finances.',
      'what_if_describe_scenario': 'Describe your scenario',
      'what_if_placeholder': 'e.g. What would happen if I buy a 10,000 laptop in 6 installments? Can I afford it?',
      'what_if_input_hint': 'Include amounts, terms and details for a better analysis',
      'what_if_analyzing': 'Analyzing scenario...',
      'what_if_analyze_btn': 'Analyze Scenario with AI',
      'what_if_analysis_result': 'Scenario Analysis 🔮',
      'what_if_empty_state': 'Write a scenario above or select one of the examples to see the AI analysis',
      'what_if_risk_low': 'Low',
      'what_if_risk_moderate': 'Moderate ⚠️',
      'what_if_risk_critical': 'Critical 🚨',
      'what_if_chip_laptop_title': 'Buy laptop in installments',
      'what_if_chip_laptop_query': 'What would happen if I buy a 10000 laptop in 6 monthly installments?',
      'what_if_chip_car_title': 'Buy car',
      'what_if_chip_car_query': 'What would happen if I buy an 80000 car with a 20000 down payment and 48-month financing?',
      'what_if_chip_salary_title': 'Salary increase',
      'what_if_chip_salary_query': 'What would happen if my salary increases by 20% starting next month?',
      'what_if_chip_rent_title': 'Rent apartment',
      'what_if_chip_rent_query': 'What would happen if I move to an apartment with rent of 3500 monthly?',
      'what_if_chip_save_title': 'Save monthly',
      'what_if_chip_save_query': 'What would happen if I start saving 1500 a month for 12 months?',
      'what_if_chip_phone_title': 'Buy phone',
      'what_if_chip_phone_query': 'What would happen if I buy an 8000 iPhone in 12 installments?',
      'what_if_chip_masters_title': 'Study master\'s degree',
      'what_if_chip_masters_query': 'What would happen if I start a master\'s degree that costs 5000 a month for 24 months?',
      'what_if_chip_job_title': 'Lose job',
      'what_if_chip_job_query': 'What would happen if I lose my job and am left without income for 3 months?',
      'error_analyzing_scenario': 'Error analyzing scenario',
      'error_obtaining_diagnosis': 'Error obtaining diagnosis from Zent AI',
    },
    'pt': {
      'settings_title': 'Configurações ⚙️',
      'settings_subtitle': 'Personalize sua experiência',
      'edit_profile': 'Editar Perfil',
      'premium_upgrade': 'Atualizar para Premium',
      'premium_desc': 'Desbloqueie todos os recursos: sem anúncios, relatórios avançados, sincronização em nuvem e mais.',
      'see_plans': 'Ver Planos',
      'general': 'Geral',
      'notifications': 'Notificações',
      'notifications_desc': 'Alertas e lembretes',
      'language': 'Idioma',
      'dark_theme': 'Tema Escuro',
      'dark_theme_desc': 'Ativar modo noturno',
      'security': 'Segurança',
      'change_password': 'Alterar Senha',
      'change_password_desc': 'Última atualização há 3 meses',
      'two_factor': 'Autenticação em Dois Fatores',
      'two_factor_desc': 'Proteja sua conta',
      'budgets': 'Orçamentos',
      'category_budget': 'Orçamento por Categoria',
      'category_budget_desc': 'Definir limites por categoria',
      'budget_alerts': 'Alertas de Orçamento',
      'budget_alerts_desc': 'Notificações ao se aproximar do limite',
      'appearance': 'Aparência',
      'color_palette': 'Paleta de Cores',
      'color_palette_desc': 'Personalize suas cores',
      'data': 'Dados',
      'cloud_sync': 'Sincronização em Nuvem',
      'cloud_sync_desc': 'Premium',
      'local_backup': 'Backup Local',
      'local_backup_desc': 'Último backup: Hoje',
      'export_data': 'Exportar Dados',
      'export_data_desc': 'Baixar em formato CSV',
      'logout': 'Sair',
      'currency': 'Moeda',
      'currency_desc': 'Selecione sua moeda local',
      'dashboard': 'Painel',
      'transactions': 'Transações',
      'expenses': 'Despesas',
      'total_balance': 'Saldo Total',
      'income': 'Receitas',
      'total_expenses': 'Despesas Totais',
      'recent_transactions': 'Transações Recentes',
      'see_all': 'Ver todas',
      'select_language': 'Selecionar Idioma',
      'select_language_desc': 'Escolha o idioma do aplicativo',
      'select_currency': 'Selecionar Moeda',
      'select_currency_desc': 'Escolha a moeda do aplicativo',
      'select_country': 'Selecionar País',
      'select_country_desc': 'Escolha seu país de residência',
      
      'complete_profile': 'Complete seu perfil!',
      'complete_profile_desc': 'Precisamos de alguns dados para personalizar sua experiência e ajudá-lo a economizar:',
      'country': 'País',
      'salary': 'Salário',
      'complete_now': 'Completar Agora',
      'fixed_expense': 'Despesa Fixa',
      'new_expense': 'Nova Despesa',
      'amount': 'Valor',
      'category': 'Categoria',
      'description_optional': 'Descrição (Opcional)',
      'date': 'Data',
      'add_expense': 'Adicionar Despesa',
      'add_fixed_expense': 'Adicionar Despesa Fixa',
      'expense_added': 'Despesa adicionada com sucesso',
      'fixed_income': 'Renda Fixa',
      'new_income': 'Nova Renda',
      'add_income': 'Adicionar Renda',
      'income_added': 'Renda adicionada com sucesso',
      'new_debt': 'Nova Dívida/Parcela',
      'total_installments': 'Parcelas Totais',
      'paid_installments': 'Parcelas Pagas',
      'add_debt': 'Adicionar Dívida',
      'debt_added': 'Dívida adicionada com sucesso',
      'home': 'Início',
      'debts': 'Dívidas',
      'savings': 'Economias',
      'profile': 'Perfil',
      'welcome_back': 'Bem-vindo de volta,',
      'your_finances': 'Aqui está o seu resumo financeiro',
      'add_first_expense': 'Adicione sua primeira despesa',
      'add_first_debt': 'Adicione sua primeira dívida',
      'save': 'Salvar',
      'cancel': 'Cancelar',
      'save_changes': 'Salvar Alterações',
      'careful': 'Cuidado! ',
      'limit_reached': 'Você atingiu ',
      'limit_monthly': '% do seu limite mensal.',
      'unlocked_badges': 'Distintivos Desbloqueados',
      'quick_actions': 'Ações Rápidas',
      'income_action': 'Renda',
      'expense_action': 'Despesa',
      'ai_assistant': 'Assistente IA',
      'on_track': 'Incrível! Você está em uma sequência 🔥',
      'my_expenses': 'Minhas Despesas 💸',
      'my_incomes': 'Meus Rendimentos 💰',
      'my_debts': 'Minhas Dívidas 💳',
      'my_savings': 'Meus Poupanças 🎯',
      'search_expenses': 'Buscar despesas...',
      'total_expenses_month': 'Total de Despesas -',
      'no_income_yet': 'Nenhuma renda registrada ainda',
      'expenses_by_category': 'Despesas por Categoria',
      'of_your_income': 'da sua renda',
      'voice_ask_payment_method': 'Esta despesa foi feita com Cartão de Crédito ou Dinheiro?',
      'voice_listening': 'Estou ouvindo...',
      'voice_tap_to_speak': 'Toque para falar',
      'voice_help_text': 'Diga seu gasto ou renda:\n"Gastei 50 no almoço"\n"Recebi 5000 de salário"',
      'voice_analyzing': 'Analisando sua voz...',
      'voice_confirm_expense': 'Confirmar Despesa',
      'voice_confirm_income': 'Confirmar Receita',
      'voice_gasto': 'Despesa',
      'voice_ingreso': 'Receita',
      'voice_payment_method': 'Método de pagamento:',
      'voice_cash': '💵 Dinheiro',
      'voice_card': '💳 Cartão',
      'voice_select_card': 'Selecione seu Cartão:',
      'voice_no_cards': 'Nenhum cartão registrado no aplicativo.',
      'voice_try_again': 'Falar novamente',
      'voice_save': 'Salvar',
      'voice_success_expense': 'Despesa registrada com sucesso!',
      'voice_success_income': 'Receita registrada com sucesso!',
      'voice_accept': 'Aceitar',
      'voice_no_amount': 'Não foi possível detectar um valor válido em: "{text}". Tente falar o número novamente.',
      'voice_paying_card_or_cash': 'Cartão ou Dinheiro?',
      'voice_answer_mic': 'Responda falando para concluir o registro...',
      'dashboard_income': 'Receitas',
      'dashboard_expenses': 'Despesas',
      'dashboard_debts': 'Dívidas',
      'dashboard_cards': 'Cartões',
      'badge_pioneer': 'Pioneiro Antigravity',
      'badge_pioneer_desc': 'Complete seu perfil e identidade',
      'badge_constant_fire': 'Fogo Constante',
      'badge_constant_fire_desc': 'Mantenha uma sequência de 7 dias contínuos',
      'badge_habit_master': 'Mestre do Hábito',
      'badge_habit_master_desc': '30 dias ininterruptos no aplicativo',
      'badge_vip_shopper': 'Comprador VIP',
      'badge_vip_shopper_desc': 'Resgate seu primeiro item na loja',
      'badge_supreme_collector': 'Colecionador Supremo',
      'badge_supreme_collector_desc': 'Adquira 5 itens ou temas exclusivos',
      'badge_financial_mind': 'Mente Financeira',
      'badge_financial_mind_desc': 'Acumule 100 pontos de experiência',
      'ai_assistant_subtitle': 'Descubra como investir seu dinheiro com base no seu negócio 💰',
      'what_if_subtitle': 'Simule variações em suas receitas, despesas ou dívidas e Zent AI preverá sua saúde financeira.',
      'rewards_shop_subtitle': 'Resgate seus pontos ganhos',
      'rewards_shop_desc': 'Desbloqueie avatares exclusivos, temas personalizados e dicas VIP para impulsionar suas finanças.',
      'rewards_shop_avatars': 'Avatares',
      'rewards_shop_themes': 'Temas',
      'rewards_shop_tips': 'Dicas Pro',
      'rewards_shop_enter': 'Entrar',
      'savings_subtitle': 'Alcance suas metas financeiras',
      'total_saved': 'Total Economizado',
      'savings_month_progress': '+12% este mês',
      'savings_guide_plan': 'Plano de Poupança Guiado',
      'savings_guide_desc': 'Descubra como economizar mais e alcançar suas metas mais rápido',
      'view_guide': 'Ver Guia',
      'add_new_goal': 'Adicionar Nova Meta',
      'my_saving_goals': 'Minhas Metas de Poupança',
      'no_goals_yet': 'Você ainda não tem metas de poupança.',
      'goal_achieved': 'Alcançado!',
      'completed': 'concluído',
      'add_funds': 'Adicionar fundos',
      'error_loading_savings': 'Erro ao carregar economias',
      'error_loading_goals': 'Erro ao carregar metas de poupança',
      'quick_actions_new_goal': 'Nova Meta de Poupança',
      'quick_actions_rewards_shop': 'Loja de Recompensas',
      'quick_actions_footer': 'Selecione uma ação para continuar',
      'quick_actions_new_badge': '{count} nova(s)',
      'nav_settings': 'Ajustes',
      'what_if_title': 'Simulador AI "What If?"',
      'what_if_tab_controls': 'Controles',
      'what_if_tab_free': 'Cenário Livre',
      'what_if_initial_desc': 'Ajuste os controles de simulação acima e pressione "Solicitar Diagnóstico ao Zent AI" para avaliar seu cenário financeiro hipotético.',
      'what_if_chart_title': 'Projeção de Fluxo de Caixa (6 Meses)',
      'what_if_panel_title': 'Painel de Simulação ⚙️',
      'what_if_additional_expense': 'Despesa Mensal Adicional',
      'what_if_income_reduction': 'Redução de Receitas',
      'what_if_new_debt_payment': 'Nova Parcela de Dívida Fixa',
      'what_if_request_diagnosis': 'Solicitar Diagnóstico ao Zent AI',
      'what_if_diagnosis_title': 'Plano de Diagnóstico Zent AI 🧠',
      'what_if_desc_title': 'O que aconteceria se...?',
      'what_if_desc_subtitle': 'Descreva qualquer cenário financeiro e a IA analisará como isso afetaria suas finanças atuais.',
      'what_if_describe_scenario': 'Descreva seu cenário',
      'what_if_placeholder': 'Ex: O que aconteceria se eu comprasse um laptop de 10.000 em 6 parcelas? Posso pagar?',
      'what_if_input_hint': 'Inclua valores, prazos e detalhes para uma melhor análise',
      'what_if_analyzing': 'Analisando cenário...',
      'what_if_analyze_btn': 'Analisar Cenário com IA',
      'what_if_analysis_result': 'Análise de Cenário 🔮',
      'what_if_empty_state': 'Escreva um cenário acima ou selecione um dos exemplos para ver a análise da IA',
      'what_if_risk_low': 'Baixo',
      'what_if_risk_moderate': 'Moderado ⚠️',
      'what_if_risk_critical': 'Crítico 🚨',
      'what_if_chip_laptop_title': 'Comprar laptop parcelado',
      'what_if_chip_laptop_query': 'O que aconteceria se eu comprasse um laptop de 10000 em 6 parcelas mensais?',
      'what_if_chip_car_title': 'Comprar carro',
      'what_if_chip_car_query': 'O que aconteceria se eu comprasse um carro de 80000 com uma entrada de 20000 e financiamento em 48 meses?',
      'what_if_chip_salary_title': 'Aumento de salário',
      'what_if_chip_salary_query': 'O que aconteceria se meu salário aumentasse 20% a partir do próximo mês?',
      'what_if_chip_rent_title': 'Alugar apartamento',
      'what_if_chip_rent_query': 'O que aconteceria se eu me mudasse para um apartamento com aluguel de 3500 mensais?',
      'what_if_chip_save_title': 'Economizar mensalmente',
      'what_if_chip_save_query': 'O que aconteceria se eu começasse a economizar 1500 por mês durante 12 meses?',
      'what_if_chip_phone_title': 'Comprar telefone',
      'what_if_chip_phone_query': 'O que aconteceria se eu comprasse um iPhone de 8000 em 12 parcelas?',
      'what_if_chip_masters_title': 'Estudar mestrado',
      'what_if_chip_masters_query': 'O que aconteceria se eu começasse um mestrado que custa 5000 por mês durante 24 meses?',
      'what_if_chip_job_title': 'Perder emprego',
      'what_if_chip_job_query': 'O que aconteceria se eu perdesse o emprego e ficasse sem renda por 3 meses?',
      'error_analyzing_scenario': 'Erro ao analisar cenário',
      'error_obtaining_diagnosis': 'Erro ao obter diagnóstico do Zent AI',
    },
    'fr': {
      'settings_title': 'Paramètres ⚙️',
      'settings_subtitle': 'Personnalisez votre expérience',
      'edit_profile': 'Modifier le Profil',
      'premium_upgrade': 'Passer à Premium',
      'premium_desc': 'Débloquez toutes les fonctionnalités : sans publicité, rapports avancés, synchronisation dans le cloud, etc.',
      'see_plans': 'Voir les Forfaits',
      'general': 'Général',
      'notifications': 'Notifications',
      'notifications_desc': 'Alertes et rappels',
      'language': 'Langue',
      'dark_theme': 'Thème Sombre',
      'dark_theme_desc': 'Activer le mode nuit',
      'security': 'Sécurité',
      'change_password': 'Changer le Mot de Passe',
      'change_password_desc': 'Dernière mise à jour il y a 3 mois',
      'two_factor': 'Authentification à Deux Facteurs',
      'two_factor_desc': 'Protégez votre compte',
      'budgets': 'Budgets',
      'category_budget': 'Budget par Catégorie',
      'category_budget_desc': 'Fixer des limites par catégorie',
      'budget_alerts': 'Alertes de Budget',
      'budget_alerts_desc': 'Notifications à l\'approche de la limite',
      'appearance': 'Apparence',
      'color_palette': 'Palette de Couleurs',
      'color_palette_desc': 'Personnalisez vos couleurs',
      'data': 'Données',
      'cloud_sync': 'Synchronisation Cloud',
      'cloud_sync_desc': 'Premium',
      'local_backup': 'Sauvegarde Locale',
      'local_backup_desc': 'Dernière sauvegarde : Aujourd\'hui',
      'export_data': 'Exporter les Données',
      'export_data_desc': 'Télécharger au format CSV',
      'logout': 'Déconnexion',
      'currency': 'Devise',
      'currency_desc': 'Sélectionnez votre devise locale',
      'dashboard': 'Tableau de Bord',
      'transactions': 'Transactions',
      'expenses': 'Dépenses',
      'total_balance': 'Solde Total',
      'income': 'Revenus',
      'total_expenses': 'Dépenses Totales',
      'recent_transactions': 'Transactions Récentes',
      'see_all': 'Voir tout',
      'select_language': 'Choisir la Langue',
      'select_language_desc': 'Choisissez la langue de l\'application',
      'select_currency': 'Choisir la Devise',
      'select_currency_desc': 'Choisissez la devise de l\'application',
      'select_country': 'Choisir le Pays',
      'select_country_desc': 'Choisissez votre pays de résidence',
      
      'complete_profile': 'Complétez votre profil !',
      'complete_profile_desc': 'Nous avons besoin de quelques données pour personnaliser votre expérience et vous aider à économiser :',
      'country': 'Pays',
      'salary': 'Salaire',
      'complete_now': 'Compléter Maintenant',
      'fixed_expense': 'Dépense Fixe',
      'new_expense': 'Nouvelle Dépense',
      'amount': 'Montant',
      'category': 'Catégorie',
      'description_optional': 'Description (Optionnel)',
      'date': 'Date',
      'add_expense': 'Ajouter une Dépense',
      'add_fixed_expense': 'Ajouter Dépense Fixe',
      'expense_added': 'Dépense ajoutée avec succès',
      'fixed_income': 'Revenu Fixe',
      'new_income': 'Nouveau Revenu',
      'add_income': 'Ajouter un Revenu',
      'income_added': 'Revenu ajouté avec succès',
      'new_debt': 'Nouvelle Dette/Mensualité',
      'total_installments': 'Mensualités Totales',
      'paid_installments': 'Mensualités Payées',
      'add_debt': 'Ajouter une Dette',
      'debt_added': 'Dette ajoutée avec succès',
      'home': 'Accueil',
      'debts': 'Dettes',
      'savings': 'Économies',
      'profile': 'Profil',
      'welcome_back': 'Bon retour,',
      'your_finances': 'Voici votre résumé financier',
      'add_first_expense': 'Ajoutez votre première dépense',
      'add_first_debt': 'Ajoutez votre première dette',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'save_changes': 'Enregistrer les Modifications',
      'careful': 'Attention ! ',
      'limit_reached': 'Vous avez atteint ',
      'limit_monthly': '% de votre limite mensuelle.',
      'unlocked_badges': 'Badges Débloqués',
      'quick_actions': 'Actions Rapides',
      'income_action': 'Revenu',
      'expense_action': 'Dépense',
      'ai_assistant': 'Assistant IA',
      'on_track': 'Incroyable ! Vous êtes sur une lancée 🔥',
      'my_expenses': 'Mes Dépenses 💸',
      'my_incomes': 'Mes Revenus 💰',
      'my_debts': 'Mes Dettes 💳',
      'my_savings': 'Mes Épargnes 🎯',
      'search_expenses': 'Rechercher des dépenses...',
      'total_expenses_month': 'Total des Dépenses -',
      'no_income_yet': 'Aucun revenu enregistré pour le moment',
      'expenses_by_category': 'Dépenses par Catégorie',
      'of_your_income': 'de vos revenus',
      'voice_ask_payment_method': 'Cette dépense a-t-elle été effectuée par Carte de Crédit ou en Espèces ?',
      'voice_listening': "Je vous écoute...",
      'voice_tap_to_speak': 'Appuyer pour parler',
      'voice_help_text': 'Dites votre dépense ou revenu :\n"J\'ai dépensé 50 pour le déjeuner"\n"Ils m\'ont payé 5000 de salaire"',
      'voice_analyzing': 'Analyse de votre voix...',
      'voice_confirm_expense': 'Confirmer la Dépense',
      'voice_confirm_income': 'Confirmer le Revenu',
      'voice_gasto': 'Dépense',
      'voice_ingreso': 'Revenu',
      'voice_payment_method': 'Mode de paiement :',
      'voice_cash': '💵 Espèces',
      'voice_card': '💳 Carte',
      'voice_select_card': 'Sélectionnez votre Carte :',
      'voice_no_cards': 'Aucune carte enregistrée dans l\'application.',
      'voice_try_again': 'Parler à nouveau',
      'voice_save': 'Enregistrer',
      'voice_success_expense': 'Dépense enregistrée avec succès !',
      'voice_success_income': 'Revenu enregistré avec succès !',
      'voice_accept': 'Accepter',
      'voice_no_amount': 'Impossible de détecter un montant valide dans : "{text}". Veuillez réessayer en disant le nombre.',
      'voice_paying_card_or_cash': 'Carte ou Espèces ?',
      'voice_answer_mic': 'Répondez en parlant pour terminer l\'enregistrement...',
      'dashboard_income': 'Revenus',
      'dashboard_expenses': 'Dépenses',
      'dashboard_debts': 'Dettes',
      'dashboard_cards': 'Cartes',
      'badge_pioneer': 'Pionnier Antigravity',
      'badge_pioneer_desc': 'Complétez votre profil et votre identité',
      'badge_constant_fire': 'Feu Constant',
      'badge_constant_fire_desc': 'Maintenir une série de 7 jours continus',
      'badge_habit_master': 'Maître de l\'Habitude',
      'badge_habit_master_desc': '30 jours ininterrompus dans l\'application',
      'badge_vip_shopper': 'Acheteur VIP',
      'badge_vip_shopper_desc': 'Échangez votre premier article dans la boutique',
      'badge_supreme_collector': 'Collectionneur Suprême',
      'badge_supreme_collector_desc': 'Acquérez 5 articles ou thèmes exclusifs',
      'badge_financial_mind': 'Esprit Financier',
      'badge_financial_mind_desc': 'Cumulez 100 points d\'expérience',
      'ai_assistant_subtitle': 'Découvrez comment investir votre argent en fonction de votre entreprise 💰',
      'what_if_subtitle': 'Simulez les variations de vos revenus, dépenses ou dettes et Zent AI prédira votre santé financière.',
      'rewards_shop_subtitle': 'Échangez vos points gagnés',
      'rewards_shop_desc': 'Débloquez des avatars exclusifs, des thèmes personnalisés et des conseils VIP pour booster vos finances.',
      'rewards_shop_avatars': 'Avatars',
      'rewards_shop_themes': 'Thèmes',
      'rewards_shop_tips': 'Conseils Pro',
      'rewards_shop_enter': 'Entrer',
      'savings_subtitle': 'Atteignez vos objectifs financiers',
      'total_saved': 'Total Épargné',
      'savings_month_progress': '+12% ce mois-ci',
      'savings_guide_plan': 'Plan d\'Épargne Guidé',
      'savings_guide_desc': 'Découvrez comment épargner plus et atteindre vos objectifs plus rapidement',
      'view_guide': 'Voir le Guide',
      'add_new_goal': 'Ajouter un Objectif',
      'my_saving_goals': 'Mes Objectifs d\'Épargne',
      'no_goals_yet': 'Vous n\'avez pas encore d\'objectifs d\'épargne.',
      'goal_achieved': 'Atteint !',
      'completed': 'terminé',
      'add_funds': 'Ajouter des fonds',
      'error_loading_savings': 'Erreur lors du chargement de l\'épargne',
      'error_loading_goals': 'Erreur lors du chargement des objectifs d\'épargne',
      'quick_actions_new_goal': 'Nouvel Objectif d\'Épargne',
      'quick_actions_rewards_shop': 'Boutique de Récompenses',
      'quick_actions_footer': 'Sélectionnez une action pour continuer',
      'quick_actions_new_badge': '{count} nouvelle(s)',
      'nav_settings': 'Paramètres',
      'what_if_title': 'Simulateur IA "What If?"',
      'what_if_tab_controls': 'Contrôles',
      'what_if_tab_free': 'Scénario Libre',
      'what_if_initial_desc': 'Ajustez les contrôles de simulation ci-dessus et appuyez sur "Demander un diagnostic à Zent AI" pour évaluer votre scénario financier hypothétique.',
      'what_if_chart_title': 'Projection des flux de trésorerie (6 mois)',
      'what_if_panel_title': 'Panneau de Simulation ⚙️',
      'what_if_additional_expense': 'Dépense Mensuelle Supplémentaire',
      'what_if_income_reduction': 'Réduction des Revenus',
      'what_if_new_debt_payment': 'Nouvelle Échéance de Dette Fixe',
      'what_if_request_diagnosis': 'Demander un Diagnostic à Zent AI',
      'what_if_diagnosis_title': 'Plan de Diagnostic Zent AI 🧠',
      'what_if_desc_title': 'Que se passerait-il si...?',
      'what_if_desc_subtitle': 'Décrivez n\'importe quel scénario financier et l\'IA analysera comment il affecterait vos finances actuelles.',
      'what_if_describe_scenario': 'Décrivez votre scénario',
      'what_if_placeholder': 'Ex: Que se passerait-il si j\'achetais un ordinateur portable à 10 000 en 6 mensualités ? Puis-je me le permettre ?',
      'what_if_input_hint': 'Incluez les montants, les délais et les détails pour une meilleure analyse',
      'what_if_analyzing': 'Analyse du scénario...',
      'what_if_analyze_btn': 'Analyser le Scénario avec l\'IA',
      'what_if_analysis_result': 'Analyse du Scénario 🔮',
      'what_if_empty_state': 'Écrivez un scénario ci-dessus ou sélectionnez l\'un des exemples pour voir l\'analyse de l\'IA',
      'what_if_risk_low': 'Faible',
      'what_if_risk_moderate': 'Modéré ⚠️',
      'what_if_risk_critical': 'Critique 🚨',
      'what_if_chip_laptop_title': 'Acheter un ordinateur portable à tempérament',
      'what_if_chip_laptop_query': 'Que se passerait-il si j\'achetais un ordinateur portable de 10000 en 6 mensualités ?',
      'what_if_chip_car_title': 'Acheter une voiture',
      'what_if_chip_car_query': 'Que se passerait-il si j\'achetais une voiture de 80000 avec un acompte de 20000 et un financement sur 48 mois ?',
      'what_if_chip_salary_title': 'Augmentation de salaire',
      'what_if_chip_salary_query': 'Que se passerait-il si mon salaire augmentait de 20% à partir du mois prochain ?',
      'what_if_chip_rent_title': 'Louer un appartement',
      'what_if_chip_rent_query': 'Que se passerait-il si je déménageais dans un appartement avec un loyer mensuel de 3500 ?',
      'what_if_chip_save_title': 'Épargner mensuellement',
      'what_if_chip_save_query': 'Que se passerait-il si je commençais à épargner 1500 par mois pendant 12 mois ?',
      'what_if_chip_phone_title': 'Acheter un téléphone',
      'what_if_chip_phone_query': 'Que se passerait-il si j\'achetais un iPhone de 8000 en 12 mensualités ?',
      'what_if_chip_masters_title': 'Faire un master',
      'what_if_chip_masters_query': 'Que se passerait-il si je commençais un master qui coûte 5000 par mois pendant 24 mois ?',
      'what_if_chip_job_title': 'Perder son emploi',
      'what_if_chip_job_query': 'Que se passerait-il si je perdais mon emploi et me retrouvais sans revenu pendant 3 mois ?',
      'error_analyzing_scenario': 'Erreur lors de l\'analyse du scénario',
      'error_obtaining_diagnosis': 'Erreur lors de l\'obtention du diagnostic de Zent AI',
    },
    'it': {
      'settings_title': 'Impostazioni ⚙️',
      'settings_subtitle': 'Personalizza la tua esperienza',
      'edit_profile': 'Modifica Profilo',
      'premium_upgrade': 'Passa a Premium',
      'premium_desc': 'Sblocca tutte le funzioni: senza pubblicità, report avanzati, sincronizzazione cloud e altro.',
      'see_plans': 'Vedi Piani',
      'general': 'Generale',
      'notifications': 'Notifiche',
      'notifications_desc': 'Avvisi e promemoria',
      'language': 'Lingua',
      'dark_theme': 'Tema Scuro',
      'dark_theme_desc': 'Abilita modalità notte',
      'security': 'Sicurezza',
      'change_password': 'Cambia Password',
      'change_password_desc': 'Ultimo aggiornamento 3 mesi fa',
      'two_factor': 'Autenticazione a Due Fattori',
      'two_factor_desc': 'Proteggi il tuo account',
      'budgets': 'Budget',
      'category_budget': 'Budget per Categoria',
      'category_budget_desc': 'Imposta limiti per categoria',
      'budget_alerts': 'Avvisi di Budget',
      'budget_alerts_desc': 'Notifiche quando ti avvicini al limite',
      'appearance': 'Aspetto',
      'color_palette': 'Tavolozza Colori',
      'color_palette_desc': 'Personalizza i tuoi colori',
      'data': 'Dati',
      'cloud_sync': 'Sincronizzazione Cloud',
      'cloud_sync_desc': 'Premium',
      'local_backup': 'Backup Locale',
      'local_backup_desc': 'Ultimo backup: Oggi',
      'export_data': 'Esporta Dati',
      'export_data_desc': 'Scarica in formato CSV',
      'logout': 'Disconnettersi',
      'currency': 'Valuta',
      'currency_desc': 'Seleziona la tua valuta locale',
      'dashboard': 'Pannello',
      'transactions': 'Transazioni',
      'expenses': 'Spese',
      'total_balance': 'Saldo Totale',
      'income': 'Reddito',
      'total_expenses': 'Spese Totali',
      'recent_transactions': 'Transazioni Recenti',
      'see_all': 'Vedi tutto',
      'select_language': 'Seleziona Lingua',
      'select_language_desc': 'Scegli la lingua dell\'applicazione',
      'select_currency': 'Seleziona Valuta',
      'select_currency_desc': 'Scegli la valuta dell\'applicazione',
      'select_country': 'Seleziona Paese',
      'select_country_desc': 'Scegli il tuo paese di residenza',
      
      'complete_profile': 'Completa il tuo profilo!',
      'complete_profile_desc': 'Abbiamo bisogno di alcuni dati per personalizzare la tua esperienza e aiutarti a risparmiare:',
      'country': 'Paese',
      'salary': 'Stipendio',
      'complete_now': 'Completa Ora',
      'fixed_expense': 'Spesa Fissa',
      'new_expense': 'Nuova Spesa',
      'amount': 'Importo',
      'category': 'Categoria',
      'description_optional': 'Descrizione (Opzionale)',
      'date': 'Data',
      'add_expense': 'Aggiungi Spesa',
      'add_fixed_expense': 'Aggiungi Spesa Fissa',
      'expense_added': 'Spesa aggiunta con successo',
      'fixed_income': 'Reddito Fisso',
      'new_income': 'Nuovo Reddito',
      'add_income': 'Aggiungi Reddito',
      'income_added': 'Reddito aggiunto con successo',
      'new_debt': 'Nuovo Debito/Rata',
      'total_installments': 'Rate Totali',
      'paid_installments': 'Rate Pagate',
      'add_debt': 'Aggiungi Debito',
      'debt_added': 'Debito aggiunto con successo',
      'home': 'Home',
      'debts': 'Debiti',
      'savings': 'Risparmi',
      'profile': 'Profilo',
      'welcome_back': 'Bentornato,',
      'your_finances': 'Ecco il tuo riepilogo finanziario',
      'add_first_expense': 'Aggiungi la tua prima spesa',
      'add_first_debt': 'Aggiungi il tuo primo debito',
      'save': 'Salva',
      'cancel': 'Annulla',
      'save_changes': 'Salva Modifiche',
      'careful': 'Attenzione! ',
      'limit_reached': 'Hai raggiunto il ',
      'limit_monthly': '% del tuo limite mensile.',
      'unlocked_badges': 'Distintivi Sbloccati',
      'quick_actions': 'Azioni Rapide',
      'income_action': 'Reddito',
      'expense_action': 'Spesa',
      'ai_assistant': 'Assistente IA',
      'on_track': 'Incredibile! Sei in una striscia 🔥',
      'my_expenses': 'Le Mie Spese 💸',
      'my_incomes': 'I Miei Redditi 💰',
      'my_debts': 'I Miei Debiti 💳',
      'my_savings': 'I Miei Risparmi 🎯',
      'search_expenses': 'Cerca spese...',
      'total_expenses_month': 'Totale Spese -',
      'no_income_yet': 'Nessun reddito registrato ancora',
      'expenses_by_category': 'Spese per Categoria',
      'of_your_income': 'del tuo reddito',
      'voice_ask_payment_method': 'Questa spesa è stata effettuata con Carta di Credito o in Contanti?',
      'voice_listening': 'Ti sto ascoltando...',
      'voice_tap_to_speak': 'Tocca per parlare',
      'voice_help_text': 'Dimmi la tua spesa o entrate:\n"Ho speso 50 per il pranzo"\n"Mi hanno pagato 5000 di stipendio"',
      'voice_analyzing': 'Analisi della tua voce...',
      'voice_confirm_expense': 'Conferma Spesa',
      'voice_confirm_income': 'Conferma Entrata',
      'voice_gasto': 'Spesa',
      'voice_ingreso': 'Entrata',
      'voice_payment_method': 'Metodo di pagamento:',
      'voice_cash': '💵 Contanti',
      'voice_card': '💳 Carta',
      'voice_select_card': 'Seleziona la tua Carta:',
      'voice_no_cards': 'Nessuna carta registrata nell\'applicazione.',
      'voice_try_again': 'Parla di nuovo',
      'voice_save': 'Salva',
      'voice_success_expense': 'Spesa registrata con successo!',
      'voice_success_income': 'Entrata registrata con successo!',
      'voice_accept': 'Accetta',
      'voice_no_amount': 'Impossibile rilevare un importo valido in: "{text}". Riprova dicendo il numero.',
      'voice_paying_card_or_cash': 'Carta o Contanti?',
      'voice_answer_mic': 'Rispondi parlando per completare la registrazione...',
      'dashboard_income': 'Entrate',
      'dashboard_expenses': 'Spese',
      'dashboard_debts': 'Debiti',
      'dashboard_cards': 'Carte',
      'badge_pioneer': 'Pioniere Antigravity',
      'badge_pioneer_desc': 'Completa il tuo profilo e identità',
      'badge_constant_fire': 'Fuoco Costante',
      'badge_constant_fire_desc': 'Mantieni una serie di 7 giorni continui',
      'badge_habit_master': 'Maestro dell\'Abitudine',
      'badge_habit_master_desc': '30 giorni ininterrotti nell\'app',
      'badge_vip_shopper': 'Acquirente VIP',
      'badge_vip_shopper_desc': 'Riscatta il tuo primo articolo nel negozio',
      'badge_supreme_collector': 'Collezionista Supremo',
      'badge_supreme_collector_desc': 'Acquista 5 articoli o temi esclusivi',
      'badge_financial_mind': 'Mente Finanziaria',
      'badge_financial_mind_desc': 'Accumula 100 punti esperienza',
      'ai_assistant_subtitle': 'Scopri come investire i tuoi soldi in base alla tua attività 💰',
      'what_if_subtitle': 'Simula le variazioni di entrate, spese o debiti e Zent AI prevederà la tua salute finanziaria.',
      'rewards_shop_subtitle': 'Riscatta i punti guadagnati',
      'rewards_shop_desc': 'Sblocca avatar esclusivi, temi personalizzati e consigli VIP per potenziare le tue finanze.',
      'rewards_shop_avatars': 'Avatar',
      'rewards_shop_themes': 'Temi',
      'rewards_shop_tips': 'Consigli Pro',
      'rewards_shop_enter': 'Entra',
      'savings_subtitle': 'Raggiungi i tuoi obiettivi finanziari',
      'total_saved': 'Totale Risparmiato',
      'savings_month_progress': '+12% questo mese',
      'savings_guide_plan': 'Piano di Risparmio Guidato',
      'savings_guide_desc': 'Scopri come risparmiare di più e raggiungere i tuoi obiettivi più velocemente',
      'view_guide': 'Vedi Guida',
      'add_new_goal': 'Aggiungi Nuovo Obiettivo',
      'my_saving_goals': 'I Miei Obiettivi di Risparmio',
      'no_goals_yet': 'Non hai ancora obiettivi di risparmio.',
      'goal_achieved': 'Raggiunto!',
      'completed': 'completato',
      'add_funds': 'Aggiungi fondi',
      'error_loading_savings': 'Errore nel caricamento dei risparmi',
      'error_loading_goals': 'Errore nel caricamento degli obiettivi',
      'quick_actions_new_goal': 'Nuovo Obiettivo di Risparmio',
      'quick_actions_rewards_shop': 'Negozio Premi',
      'quick_actions_footer': 'Seleziona un\'azione per continuare',
      'quick_actions_new_badge': '{count} nuova(e)',
      'nav_settings': 'Impostazioni',
      'what_if_title': 'Simulatore AI "What If?"',
      'what_if_tab_controls': 'Controlli',
      'what_if_tab_free': 'Scenario Libero',
      'what_if_initial_desc': 'Regola i controlli di simulazione sopra e premi "Richiedi Diagnosi a Zent AI" per valutare il tuo scenario finanziario ipotetico.',
      'what_if_chart_title': 'Proiezione del Flusso di Cassa (6 Mesi)',
      'what_if_panel_title': 'Pannello di Simulazione ⚙️',
      'what_if_additional_expense': 'Spesa Mensile Aggiuntiva',
      'what_if_income_reduction': 'Riduzione delle Entrate',
      'what_if_new_debt_payment': 'Nuova Rata del Debito Fisso',
      'what_if_request_diagnosis': 'Richiedi Diagnosi a Zent AI',
      'what_if_diagnosis_title': 'Piano Diagnostico Zent AI 🧠',
      'what_if_desc_title': 'Cosa succederebbe se...?',
      'what_if_desc_subtitle': 'Descrivi qualsiasi scenario finanziario e l\'IA analizzerà come influenzerebbe le tue finanze attuali.',
      'what_if_describe_scenario': 'Descrivi il tuo scenario',
      'what_if_placeholder': 'Es: Cosa succederebbe se acquistassi un laptop da 10.000 in 6 rate? Posso permettermelo?',
      'what_if_input_hint': 'Includi importi, scadenze e dettagli per una migliore analisi',
      'what_if_analyzing': 'Analisi dello scenario...',
      'what_if_analyze_btn': 'Analizza Scenario con IA',
      'what_if_analysis_result': 'Analisi dello Scenario 🔮',
      'what_if_empty_state': 'Scrivi uno scenario sopra o seleziona uno degli esempi per vedere l\'analisi dell\'IA',
      'what_if_risk_low': 'Basso',
      'what_if_risk_moderate': 'Moderato ⚠️',
      'what_if_risk_critical': 'Critico 🚨',
      'what_if_chip_laptop_title': 'Acquista laptop a rate',
      'what_if_chip_laptop_query': 'Cosa succederebbe se acquistassi un laptop da 10000 in 6 rate mensili?',
      'what_if_chip_car_title': 'Acquista auto',
      'what_if_chip_car_query': 'Cosa succederebbe se acquistassi un\'auto da 80000 con un acconto di 20000 e un finanziamento a 48 mesi?',
      'what_if_chip_salary_title': 'Aumento di stipendio',
      'what_if_chip_salary_query': 'Cosa succederebbe se il mio stipendio aumentasse del 20% a partire dal mese prossimo?',
      'what_if_chip_rent_title': 'Affitta appartamento',
      'what_if_chip_rent_query': 'Cosa succederebbe se mi trasferissi in un appartamento con un affitto mensile di 3500?',
      'what_if_chip_save_title': 'Risparmia mensilmente',
      'what_if_chip_save_query': 'Cosa succederebbe se iniziassi a risparmiare 1500 al mese per 12 mesi?',
      'what_if_chip_phone_title': 'Acquista telefono',
      'what_if_chip_phone_query': 'Cosa succederebbe se acquistassi un iPhone da 8000 in 12 rate?',
      'what_if_chip_masters_title': 'Studia per un master',
      'what_if_chip_masters_query': 'Cosa succederebbe se iniziassi un master che costa 5000 al mese per 24 mesi?',
      'what_if_chip_job_title': 'Perdi il lavoro',
      'what_if_chip_job_query': 'Cosa succerebbe se perdessi il lavoro e rimanessi senza entrate per 3 mesi?',
      'error_analyzing_scenario': 'Errore durante l\'analisi dello scenario',
      'error_obtaining_diagnosis': 'Errore nell\'ottenere la diagnosi da Zent AI',
    }
  };

  String get(String key) {
    String mappedCode = intlLocale;
    final val = _localizedValues[mappedCode]?[key] ?? _localizedValues['es']?[key];
    if (val != null) return val;
    return _fallbackTranslate(key, mappedCode);
  }

  String formatRecurrenceDay(String? recurrenceType, int? recurrenceDay, [int? recurrenceDay2]) {
    final lang = intlLocale;
    final day1 = recurrenceDay ?? 1;
    final day2 = recurrenceDay2 ?? 30;
    if (recurrenceType == 'weekly') {
      final idx = day1.clamp(1, 7);
      if (lang == 'en') return ['', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][idx];
      if (lang == 'pt') return ['', 'Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado', 'Domingo'][idx];
      if (lang == 'fr') return ['', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'][idx];
      if (lang == 'it') return ['', 'Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato', 'Domenica'][idx];
      return ['', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'][idx];
    }
    if (recurrenceType == 'bimonthly') {
      if (lang == 'en') return 'Days $day1 & $day2';
      if (lang == 'pt') return 'Dias $day1 e $day2';
      if (lang == 'fr') return 'Jours $day1 et $day2';
      if (lang == 'it') return 'Giorni $day1 e $day2';
      return 'Días $day1 y $day2';
    }
    if (lang == 'en') return 'Day $day1 of every month';
    if (lang == 'pt') return 'Dia $day1 de cada mês';
    if (lang == 'fr') return 'Jour $day1 de chaque mois';
    if (lang == 'it') return 'Giorno $day1 di ogni mese';
    return 'Día $day1 de cada mes';
  }

  String formatRecurrenceSubtitle(String? recurrenceType, int? recurrenceDay, [int? recurrenceDay2]) {
    final lang = intlLocale;
    final day1 = recurrenceDay ?? 1;
    final day2 = recurrenceDay2 ?? 30;
    final freq = get(recurrenceType == 'weekly' ? 'weekly' : (recurrenceType == 'bimonthly' ? 'bimonthly' : 'monthly'));
    if (recurrenceType == 'weekly') {
      final idx = day1.clamp(1, 7);
      String shortDay;
      if (lang == 'en') shortDay = ['', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][idx];
      else if (lang == 'pt') shortDay = ['', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'][idx];
      else if (lang == 'fr') shortDay = ['', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'][idx];
      else if (lang == 'it') shortDay = ['', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab', 'Dom'][idx];
      else shortDay = ['', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'][idx];
      return '$shortDay • $freq';
    }
    if (recurrenceType == 'bimonthly') {
      if (lang == 'en') return 'Days $day1 & $day2 • $freq';
      if (lang == 'pt') return 'Dias $day1 e $day2 • $freq';
      if (lang == 'fr') return 'Jours $day1 et $day2 • $freq';
      if (lang == 'it') return 'Giorni $day1 e $day2 • $freq';
      return 'Días $day1 y $day2 • $freq';
    }
    if (lang == 'en') return 'Day $day1 • $freq';
    if (lang == 'pt') return 'Dia $day1 • $freq';
    if (lang == 'fr') return 'Jour $day1 • $freq';
    if (lang == 'it') return 'Giorno $day1 • $freq';
    return 'Día $day1 • $freq';
  }

  String getCategoryEmoji(String category) {
    if (category.runes.isNotEmpty && category.runes.first > 127 && category.length <= 4) return category;
    final clean = category.toLowerCase().trim();
    const map = {
      'food': '🍔', 'food_grocery': '🛒', 'food_restaurant': '🍽️', 'food_coffee': '☕', 'food_delivery': '🛵',
      'transport': '🚗', 'transport_gas': '⛽', 'transport_public': '🚌', 'transport_taxi': '🚕', 'transport_flight': '✈️',
      'bills': '📱', 'bills_water': '💧', 'bills_electricity': '⚡', 'bills_internet': '🌐', 'bills_gas': '🔥',
      'shopping': '🛍️', 'shopping_clothes': '👕', 'shopping_electronics': '💻', 'shopping_gifts': '🎁',
      'entertainment': '🎮', 'entertainment_movies': '🍿', 'entertainment_music': '🎵', 'entertainment_sports': '⚽', 'entertainment_subscriptions': '📺',
      'health': '💊', 'health_doctor': '👨‍⚕️', 'health_pharmacy': '🏥', 'health_gym': '🏋️',
      'home': '🏠', 'home_rent': '🏢', 'home_maintenance': '🔧', 'home_furniture': '🛋️',
      'education': '📚', 'education_tuition': '🎓', 'education_books': '📖', 'education_courses': '🖥️',
      'other': '💸', 'salary': '💼', 'freelance': '💻', 'investments': '📈', 'investment': '📈', 'dividends': '💸', 'bonus': '🎁', 'sale': '🏷️', 'business': '🏢',
      'gifts': '🎁', 'gift': '🎉', 'car': '🚗', 'rent': '🏠', 'alquiler de casa': '🏠', 'credit_card': '💳',
      'subscription': '📺', 'loan': '🏦', 'streak': '🔥', 'alert': '⚠️', 'ai': '🤖', 'debt': '💳',
    };
    if (map.containsKey(clean)) return map[clean]!;
    final mainCat = clean.split('_')[0];
    return map[mainCat] ?? '💰';
  }

  String translateCategory(String code) {
    if (code.runes.isNotEmpty && code.runes.first > 127 && code.length <= 4) return code;
    final clean = code.toLowerCase().trim();
    String mappedCode = intlLocale;

    final mapEs = {
      'food': 'Comida',
      'food_grocery': 'Supermercado',
      'food_restaurant': 'Restaurante',
      'food_coffee': 'Cafetería',
      'food_delivery': 'Delivery',
      'transport': 'Transporte',
      'transport_gas': 'Gasolina',
      'transport_public': 'Transporte Público',
      'transport_taxi': 'Taxi / App',
      'transport_flight': 'Vuelos',
      'bills': 'Servicios',
      'bills_water': 'Agua',
      'bills_electricity': 'Luz',
      'bills_internet': 'Internet / TV',
      'bills_gas': 'Gas',
      'shopping': 'Compras',
      'shopping_clothes': 'Ropa y Calzado',
      'shopping_electronics': 'Electrónica',
      'shopping_gifts': 'Regalos',
      'entertainment': 'Entretenimiento',
      'entertainment_movies': 'Cine',
      'entertainment_music': 'Música',
      'entertainment_sports': 'Deportes',
      'entertainment_subscriptions': 'Suscripciones',
      'health': 'Salud',
      'health_doctor': 'Médico',
      'health_pharmacy': 'Farmacia',
      'health_gym': 'Gimnasio',
      'home': 'Hogar',
      'home_rent': 'Alquiler / Hipoteca',
      'home_maintenance': 'Mantenimiento',
      'home_furniture': 'Muebles',
      'education': 'Educación',
      'education_tuition': 'Colegiatura',
      'education_books': 'Libros / Material',
      'education_courses': 'Cursos',
      'other': 'Otros',
      'salary': 'Salario',
      'freelance': 'Freelance',
      'investments': 'Inversiones',
      'investment': 'Inversiones',
      'dividends': 'Dividendos',
      'bonus': 'Bonificación',
      'sale': 'Venta de Activos',
      'business': 'Negocio',
      'gifts': 'Regalos',
      'gift': 'Regalo',
      'car': 'Carro / Vehículo',
      'rent': 'Alquiler de casa',
      'alquiler de casa': 'Alquiler de casa',
      'credit_card': 'Tarjeta de Crédito',
      'subscription': 'Suscripción',
      'loan': 'Préstamo',
      'streak': 'Racha',
      'alert': 'Alerta',
      'ai': 'Asistente AI',
      'debt': 'Cuotas de Deudas',
      'cc_payment': 'Pago de Tarjeta',
    };

    final mapEn = {
      'food': 'Food',
      'food_grocery': 'Groceries',
      'food_restaurant': 'Restaurant',
      'food_coffee': 'Coffee Shop',
      'food_delivery': 'Delivery',
      'transport': 'Transport',
      'transport_gas': 'Gasoline',
      'transport_public': 'Public Transport',
      'transport_taxi': 'Taxi / App',
      'transport_flight': 'Flights',
      'bills': 'Bills & Utilities',
      'bills_water': 'Water',
      'bills_electricity': 'Electricity',
      'bills_internet': 'Internet / TV',
      'bills_gas': 'Gas',
      'shopping': 'Shopping',
      'shopping_clothes': 'Clothes & Shoes',
      'shopping_electronics': 'Electronics',
      'shopping_gifts': 'Gifts',
      'entertainment': 'Entertainment',
      'entertainment_movies': 'Movies',
      'entertainment_music': 'Music',
      'entertainment_sports': 'Sports',
      'entertainment_subscriptions': 'Subscriptions',
      'health': 'Health',
      'health_doctor': 'Doctor',
      'health_pharmacy': 'Pharmacy',
      'health_gym': 'Gym',
      'home': 'Home',
      'home_rent': 'Rent / Mortgage',
      'home_maintenance': 'Maintenance',
      'home_furniture': 'Furniture',
      'education': 'Education',
      'education_tuition': 'Tuition',
      'education_books': 'Books / Supplies',
      'education_courses': 'Courses',
      'other': 'Other',
      'salary': 'Salary',
      'freelance': 'Freelance',
      'investments': 'Investments',
      'investment': 'Investments',
      'dividends': 'Dividends',
      'bonus': 'Bonus',
      'sale': 'Asset Sale',
      'business': 'Business',
      'gifts': 'Gifts',
      'gift': 'Gift',
      'car': 'Car / Vehicle',
      'rent': 'House Rent',
      'alquiler de casa': 'House Rent',
      'credit_card': 'Credit Card',
      'subscription': 'Subscription',
      'loan': 'Loan',
      'streak': 'Streak',
      'alert': 'Alert',
      'ai': 'AI Assistant',
      'debt': 'Debt Installments',
      'cc_payment': 'Card Payment',
    };

    final mapPt = {
      'food': 'Alimentação',
      'food_grocery': 'Supermercado',
      'food_restaurant': 'Restaurante',
      'food_coffee': 'Cafeteria',
      'food_delivery': 'Delivery',
      'transport': 'Transporte',
      'transport_gas': 'Gasolina',
      'transport_public': 'Transporte Público',
      'transport_taxi': 'Táxi / App',
      'transport_flight': 'Voos',
      'bills': 'Contas e Serviços',
      'bills_water': 'Água',
      'bills_electricity': 'Luz',
      'bills_internet': 'Internet / TV',
      'bills_gas': 'Gás',
      'shopping': 'Compras',
      'shopping_clothes': 'Roupas e Calçados',
      'shopping_electronics': 'Eletrônicos',
      'shopping_gifts': 'Presentes',
      'entertainment': 'Entretenimento',
      'entertainment_movies': 'Cinema',
      'entertainment_music': 'Música',
      'entertainment_sports': 'Esportes',
      'entertainment_subscriptions': 'Assinaturas',
      'health': 'Saúde',
      'health_doctor': 'Médico',
      'health_pharmacy': 'Farmácia',
      'health_gym': 'Academia',
      'home': 'Casa',
      'home_rent': 'Aluguel / Hipoteca',
      'home_maintenance': 'Manutenção',
      'home_furniture': 'Móveis',
      'education': 'Educação',
      'education_tuition': 'Mensalidade',
      'education_books': 'Livros / Materiais',
      'education_courses': 'Cursos',
      'other': 'Outros',
      'salary': 'Salário',
      'freelance': 'Freelance',
      'investments': 'Investimentos',
      'investment': 'Investimentos',
      'dividends': 'Dividendos',
      'bonus': 'Bônus',
      'sale': 'Venda de Ativos',
      'business': 'Negócios',
      'gifts': 'Presentes',
      'gift': 'Presente',
      'car': 'Carro / Veículo',
      'rent': 'Aluguel de casa',
      'alquiler de casa': 'Aluguel de casa',
      'credit_card': 'Cartão de Crédito',
      'subscription': 'Assinatura',
      'loan': 'Empréstimo',
      'streak': 'Sequência',
      'alert': 'Alerta',
      'ai': 'Assistente IA',
      'debt': 'Parcelas de Dívida',
      'cc_payment': 'Pagamento de Cartão',
    };

    final mapFr = {
      'food': 'Nourriture',
      'food_grocery': 'Supermarché',
      'food_restaurant': 'Restaurant',
      'food_coffee': 'Café',
      'food_delivery': 'Livraison',
      'transport': 'Transport',
      'transport_gas': 'Essence',
      'transport_public': 'Transport en commun',
      'transport_taxi': 'Taxi / App',
      'transport_flight': 'Vols',
      'bills': 'Factures et Services',
      'bills_water': 'Eau',
      'bills_electricity': 'Électricité',
      'bills_internet': 'Internet / TV',
      'bills_gas': 'Gaz',
      'shopping': 'Achats',
      'shopping_clothes': 'Vêtements',
      'shopping_electronics': 'Électronique',
      'shopping_gifts': 'Cadeaux',
      'entertainment': 'Divertissement',
      'entertainment_movies': 'Cinéma',
      'entertainment_music': 'Musique',
      'entertainment_sports': 'Sports',
      'entertainment_subscriptions': 'Abonnements',
      'health': 'Santé',
      'health_doctor': 'Médecin',
      'health_pharmacy': 'Pharmacie',
      'health_gym': 'Salle de sport',
      'home': 'Maison',
      'home_rent': 'Loyer / Hypothèque',
      'home_maintenance': 'Entretien',
      'home_furniture': 'Meubles',
      'education': 'Éducation',
      'education_tuition': 'Scolarité',
      'education_books': 'Livres / Fournitures',
      'education_courses': 'Cours',
      'other': 'Autres',
      'salary': 'Salaire',
      'freelance': 'Freelance',
      'investments': 'Investissements',
      'investment': 'Investissements',
      'dividends': 'Dividendes',
      'bonus': 'Prime',
      'sale': "Vente d'actifs",
      'business': 'Affaires',
      'gifts': 'Cadeaux',
      'gift': 'Cadeau',
      'car': 'Voiture',
      'rent': 'Loyer',
      'alquiler de casa': 'Loyer',
      'credit_card': 'Carte de Crédit',
      'subscription': 'Abonnement',
      'loan': 'Prêt',
      'streak': 'Série',
      'alert': 'Alerte',
      'ai': 'Assistant IA',
      'debt': 'Mensualités',
      'cc_payment': 'Paiement de Carte',
    };

    final mapIt = {
      'food': 'Cibo',
      'food_grocery': 'Supermercato',
      'food_restaurant': 'Ristorante',
      'food_coffee': 'Caffetteria',
      'food_delivery': 'Consegna',
      'transport': 'Trasporti',
      'transport_gas': 'Benzina',
      'transport_public': 'Trasporto Pubblico',
      'transport_taxi': 'Taxi / App',
      'transport_flight': 'Voli',
      'bills': 'Bollette e Servizi',
      'bills_water': 'Acqua',
      'bills_electricity': 'Luce',
      'bills_internet': 'Internet / TV',
      'bills_gas': 'Gas',
      'shopping': 'Acquisti',
      'shopping_clothes': 'Abbigliamento',
      'shopping_electronics': 'Elettronica',
      'shopping_gifts': 'Regali',
      'entertainment': 'Intrattenimento',
      'entertainment_movies': 'Cinema',
      'entertainment_music': 'Musica',
      'entertainment_sports': 'Sport',
      'entertainment_subscriptions': 'Abbonamenti',
      'health': 'Salute',
      'health_doctor': 'Medico',
      'health_pharmacy': 'Farmacia',
      'health_gym': 'Palestra',
      'home': 'Casa',
      'home_rent': 'Affitto / Mutuo',
      'home_maintenance': 'Manutenzione',
      'home_furniture': 'Mobili',
      'education': 'Istruzione',
      'education_tuition': 'Retta Scolastica',
      'education_books': 'Libri / Materiali',
      'education_courses': 'Corsi',
      'other': 'Altri',
      'salary': 'Stipendio',
      'freelance': 'Freelance',
      'investments': 'Investimenti',
      'investment': 'Investimenti',
      'dividends': 'Dividendi',
      'bonus': 'Bonus',
      'sale': 'Vendita di beni',
      'business': 'Affari',
      'gifts': 'Regali',
      'gift': 'Regalo',
      'car': 'Auto / Veicolo',
      'rent': 'Affitto casa',
      'alquiler de casa': 'Affitto casa',
      'credit_card': 'Carta di Credito',
      'subscription': 'Abbonamento',
      'loan': 'Prestito',
      'streak': 'Serie',
      'alert': 'Avviso',
      'ai': 'Assistente IA',
      'debt': 'Rate Debito',
      'cc_payment': 'Pagamento Carta',
    };

    if (mappedCode == 'en') return mapEn[clean] ?? mapEs[clean] ?? code;
    if (mappedCode == 'pt') return mapPt[clean] ?? mapEs[clean] ?? code;
    if (mappedCode == 'fr') return mapFr[clean] ?? mapEs[clean] ?? code;
    if (mappedCode == 'it') return mapIt[clean] ?? mapEs[clean] ?? code;
    return mapEs[clean] ?? code;
  }

  String _fallbackTranslate(String key, String mappedCode) {
    final clean = key.toLowerCase().trim();
    final esMap = {
      'history': 'Historial',
      'no_transactions': 'Sin movimientos registrados',
      'frequency': 'Frecuencia',
      'billing_day': 'Día de cobro',
      'understood': 'Entendido',
      'weekly': 'Semanal',
      'bimonthly': 'Quincenal',
      'monthly': 'Mensual',
      'credit_card_history': 'Historial de Tarjeta',
      'credit_cards': 'Tarjetas de Crédito',
      'accounts_cash': 'Cuentas y Efectivo',
      'today_expenses': 'Gastos de hoy',
      'today_income': 'Ingresos de hoy',
      'recent_activity': 'Actividad Reciente',
      'subscriptions': 'Suscripciones y Gastos Fijos',
      'pay': 'Abonar',
      'details': 'Detalles',
      'fixed': 'Fijo',
      'select_category': 'Selecciona Categoría',
    };
    final enMap = {
      'history': 'History',
      'no_transactions': 'No transactions recorded',
      'frequency': 'Frequency',
      'billing_day': 'Billing Day',
      'understood': 'Got it',
      'weekly': 'Weekly',
      'bimonthly': 'Bi-weekly',
      'monthly': 'Monthly',
      'credit_card_history': 'Card History',
      'credit_cards': 'Credit Cards',
      'accounts_cash': 'Accounts & Cash',
      'today_expenses': "Today's Expenses",
      'today_income': "Today's Income",
      'recent_activity': 'Recent Activity',
      'subscriptions': 'Subscriptions & Fixed Expenses',
      'pay': 'Pay',
      'details': 'Details',
      'fixed': 'Fixed',
      'select_category': 'Select Category',
    };
    final ptMap = {
      'history': 'Histórico',
      'no_transactions': 'Sem transações registradas',
      'frequency': 'Frequência',
      'billing_day': 'Dia de cobrança',
      'understood': 'Entendido',
      'weekly': 'Semanal',
      'bimonthly': 'Quinzenal',
      'monthly': 'Mensal',
      'credit_card_history': 'Histórico do Cartão',
      'credit_cards': 'Cartões de Crédito',
      'accounts_cash': 'Contas e Dinheiro',
      'today_expenses': 'Gastos de hoje',
      'today_income': 'Receitas de hoje',
      'recent_activity': 'Atividade Recente',
      'subscriptions': 'Assinaturas e Gastos Fixos',
      'pay': 'Pagar',
      'details': 'Detalhes',
      'fixed': 'Fixo',
      'select_category': 'Selecione a Categoria',
    };
    final frMap = {
      'history': 'Historique',
      'no_transactions': 'Aucune transaction enregistrée',
      'frequency': 'Fréquence',
      'billing_day': 'Jour de facturation',
      'understood': 'Compris',
      'weekly': 'Hebdomadaire',
      'bimonthly': 'Bimensuel',
      'monthly': 'Mensuel',
      'credit_card_history': 'Historique de Carte',
      'credit_cards': 'Cartes de Crédit',
      'accounts_cash': 'Comptes & Espèces',
      'today_expenses': "Dépenses d'aujourd'hui",
      'today_income': "Revenus d'aujourd'hui",
      'recent_activity': 'Activité Récente',
      'subscriptions': 'Abonnements et Frais Fixes',
      'pay': 'Payer',
      'details': 'Détails',
      'fixed': 'Fixe',
      'select_category': 'Sélectionner la catégorie',
    };
    final itMap = {
      'history': 'Cronologia',
      'no_transactions': 'Nessuna transazione registrata',
      'frequency': 'Frequenza',
      'billing_day': 'Giorno di addebito',
      'understood': 'Capito',
      'weekly': 'Settimanale',
      'bimonthly': 'Quindicinale',
      'monthly': 'Mensile',
      'credit_card_history': 'Cronologia Carta',
      'credit_cards': 'Carte di Credito',
      'accounts_cash': 'Conti e Contanti',
      'today_expenses': 'Spese di oggi',
      'today_income': 'Entrate di oggi',
      'recent_activity': 'Attività Recente',
      'subscriptions': 'Abbonamenti e Spese Fisse',
      'pay': 'Pagare',
      'details': 'Dettagli',
      'fixed': 'Fisso',
      'select_category': 'Seleziona Categoria',
    };

    if (mappedCode == 'en') return enMap[clean] ?? esMap[clean] ?? key;
    if (mappedCode == 'pt') return ptMap[clean] ?? esMap[clean] ?? key;
    if (mappedCode == 'fr') return frMap[clean] ?? esMap[clean] ?? key;
    if (mappedCode == 'it') return itMap[clean] ?? esMap[clean] ?? key;
    return esMap[clean] ?? key;
  }
}
