import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../presentation/providers/auth_provider.dart';

final localizationProvider = Provider<AppLocalizations>((ref) {
  final langCode = ref.watch(authProvider).user?.language ?? 'es';
  return AppLocalizations(langCode);
});

class AppLocalizations {
  final String langCode;

  AppLocalizations(this.langCode);

  String get intlLocale {
    final lower = langCode.toLowerCase();
    if (lower == 'español' || lower == 'es') return 'es';
    if (lower == 'english' || lower == 'en') return 'en';
    if (lower == 'português' || lower == 'pt') return 'pt';
    if (lower == 'français' || lower == 'fr') return 'fr';
    if (lower == 'italiano' || lower == 'it') return 'it';
    return 'es'; // default fallback
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'es': {
      'settings_title': 'Configuración ⚙️',
      'settings_subtitle': 'Personaliza tu experiencia',
      'edit_profile': 'Editar Perfil',
      'premium_upgrade': 'Actualizar a Premium',
      'premium_desc': 'Desbloquea todas las funciones: sin anuncios, reportes avanzados, sincronización en la nube y más.',
      'see_plans': 'Ver Planes',
      'general': 'General',
      'notifications': 'Notificaciones',
      'notifications_desc': 'Alertas y recordatorios',
      'language': 'Idioma',
      'dark_theme': 'Tema Oscuro',
      'dark_theme_desc': 'Activar modo nocturno',
      'security': 'Seguridad',
      'change_password': 'Cambiar Contraseña',
      'change_password_desc': 'Última actualización hace 3 meses',
      'two_factor': 'Autenticación de Dos Factores',
      'two_factor_desc': 'Protege tu cuenta',
      'budgets': 'Presupuestos',
      'category_budget': 'Presupuesto por Categoría',
      'category_budget_desc': 'Establece límites por rubro',
      'budget_alerts': 'Alertas de Presupuesto',
      'budget_alerts_desc': 'Notificaciones al acercarte al límite',
      'appearance': 'Apariencia',
      'color_palette': 'Paleta de Colores',
      'color_palette_desc': 'Personaliza tus colores',
      'data': 'Datos',
      'cloud_sync': 'Sincronización en la Nube',
      'cloud_sync_desc': 'Premium',
      'local_backup': 'Respaldo Local',
      'local_backup_desc': 'Último respaldo: Hoy',
      'export_data': 'Exportar Datos',
      'export_data_desc': 'Descargar en formato CSV',
      'logout': 'Cerrar Sesión',
      'currency': 'Moneda',
      'currency_desc': 'Selecciona tu moneda local',
      'dashboard': 'Dashboard',
      'transactions': 'Transacciones',
      'expenses': 'Gastos',
      'total_balance': 'Balance Total',
      'income': 'Ingresos',
      'total_expenses': 'Gastos Totales',
      'recent_transactions': 'Transacciones Recientes',
      'see_all': 'Ver todas',
      'select_language': 'Seleccionar Idioma',
      'select_language_desc': 'Elige el idioma de la aplicación',
      'select_currency': 'Seleccionar Moneda',
      'select_currency_desc': 'Elige la moneda de la aplicación',
      'select_country': 'Seleccionar País',
      'select_country_desc': 'Elige tu país de residencia',
      
      'complete_profile': '¡Completa tu perfil!',
      'complete_profile_desc': 'Necesitamos algunos datos para personalizar tu experiencia y ayudarte a ahorrar:',
      'country': 'País',
      'salary': 'Salario',
      'complete_now': 'Completar Ahora',
      'fixed_expense': 'Gasto Fijo',
      'new_expense': 'Nuevo Gasto',
      'amount': 'Monto',
      'category': 'Categoría',
      'description_optional': 'Descripción (Opcional)',
      'date': 'Fecha',
      'add_expense': 'Agregar Gasto',
      'add_fixed_expense': 'Agregar Gasto Fijo',
      'expense_added': 'Gasto agregado exitosamente',
      'fixed_income': 'Ingreso Fijo',
      'new_income': 'Nuevo Ingreso',
      'add_income': 'Agregar Ingreso',
      'income_added': 'Ingreso agregado exitosamente',
      'new_debt': 'Nueva Deuda/Cuota',
      'total_installments': 'Cuotas Totales',
      'paid_installments': 'Cuotas Pagadas',
      'add_debt': 'Agregar Deuda',
      'debt_added': 'Deuda agregada exitosamente',
      'home': 'Inicio',
      'debts': 'Deudas',
      'savings': 'Ahorros',
      'profile': 'Perfil',
      'welcome_back': '¡Hola de nuevo,',
      'your_finances': 'Aquí está tu resumen financiero',
      'add_first_expense': 'Agrega tu primer gasto',
      'add_first_debt': 'Agrega tu primera deuda',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'save_changes': 'Guardar Cambios',
      'careful': '¡Cuidado! ',
      'limit_reached': 'Has alcanzado el ',
      'limit_monthly': '% del límite mensual.',
      'unlocked_badges': 'Insignias Desbloqueadas',
      'quick_actions': 'Acciones Rápidas',
      'income_action': 'Ingreso',
      'expense_action': 'Gasto',
      'ai_assistant': 'Asistente IA',
      'on_track': '¡Increíble! Estás en racha 🔥',
      'my_expenses': 'Mis Gastos 💸',
      'my_incomes': 'Mis Ingresos 💰',
      'my_debts': 'Mis Deudas 💳',
      'my_savings': 'Mis Ahorros 🎯',
      'search_expenses': 'Buscar gastos...',
      'total_expenses_month': 'Total de Gastos -',
      'no_income_yet': 'Sin ingresos registrados aún',
      'expenses_by_category': 'Gastos por Categoría',
      'of_your_income': 'de tus ingresos',
    },
    'en': {
      'settings_title': 'Settings ⚙️',
      'settings_subtitle': 'Customize your experience',
      'edit_profile': 'Edit Profile',
      'premium_upgrade': 'Upgrade to Premium',
      'premium_desc': 'Unlock all features: ad-free, advanced reports, cloud sync, and more.',
      'see_plans': 'View Plans',
      'general': 'General',
      'notifications': 'Notifications',
      'notifications_desc': 'Alerts and reminders',
      'language': 'Language',
      'dark_theme': 'Dark Theme',
      'dark_theme_desc': 'Enable night mode',
      'security': 'Security',
      'change_password': 'Change Password',
      'change_password_desc': 'Last updated 3 months ago',
      'two_factor': 'Two-Factor Authentication',
      'two_factor_desc': 'Protect your account',
      'budgets': 'Budgets',
      'category_budget': 'Category Budget',
      'category_budget_desc': 'Set limits by category',
      'budget_alerts': 'Budget Alerts',
      'budget_alerts_desc': 'Notifications when approaching limit',
      'appearance': 'Appearance',
      'color_palette': 'Color Palette',
      'color_palette_desc': 'Customize your colors',
      'data': 'Data',
      'cloud_sync': 'Cloud Sync',
      'cloud_sync_desc': 'Premium',
      'local_backup': 'Local Backup',
      'local_backup_desc': 'Last backup: Today',
      'export_data': 'Export Data',
      'export_data_desc': 'Download as CSV',
      'logout': 'Log Out',
      'currency': 'Currency',
      'currency_desc': 'Select your local currency',
      'dashboard': 'Dashboard',
      'transactions': 'Transactions',
      'expenses': 'Expenses',
      'total_balance': 'Total Balance',
      'income': 'Income',
      'total_expenses': 'Total Expenses',
      'recent_transactions': 'Recent Transactions',
      'see_all': 'See all',
      'select_language': 'Select Language',
      'select_language_desc': 'Choose the application language',
      'select_currency': 'Select Currency',
      'select_currency_desc': 'Choose the application currency',
      'select_country': 'Select Country',
      'select_country_desc': 'Choose your country of residence',
      
      'complete_profile': 'Complete your profile!',
      'complete_profile_desc': 'We need some data to customize your experience and help you save:',
      'country': 'Country',
      'salary': 'Salary',
      'complete_now': 'Complete Now',
      'fixed_expense': 'Fixed Expense',
      'new_expense': 'New Expense',
      'amount': 'Amount',
      'category': 'Category',
      'description_optional': 'Description (Optional)',
      'date': 'Date',
      'add_expense': 'Add Expense',
      'add_fixed_expense': 'Add Fixed Expense',
      'expense_added': 'Expense added successfully',
      'fixed_income': 'Fixed Income',
      'new_income': 'New Income',
      'add_income': 'Add Income',
      'income_added': 'Income added successfully',
      'new_debt': 'New Debt/Installment',
      'total_installments': 'Total Installments',
      'paid_installments': 'Paid Installments',
      'add_debt': 'Add Debt',
      'debt_added': 'Debt added successfully',
      'home': 'Home',
      'debts': 'Debts',
      'savings': 'Savings',
      'profile': 'Profile',
      'welcome_back': 'Welcome back,',
      'your_finances': 'Here is your financial summary',
      'add_first_expense': 'Add your first expense',
      'add_first_debt': 'Add your first debt',
      'save': 'Save',
      'cancel': 'Cancel',
      'save_changes': 'Save Changes',
      'careful': 'Careful! ',
      'limit_reached': 'You have reached ',
      'limit_monthly': '% of your monthly limit.',
      'unlocked_badges': 'Unlocked Badges',
      'quick_actions': 'Quick Actions',
      'income_action': 'Income',
      'expense_action': 'Expense',
      'ai_assistant': 'AI Assistant',
      'on_track': 'Incredible! You are on a streak 🔥',
      'my_expenses': 'My Expenses 💸',
      'my_incomes': 'My Income 💰',
      'my_debts': 'My Debts 💳',
      'my_savings': 'My Savings 🎯',
      'search_expenses': 'Search expenses...',
      'total_expenses_month': 'Total Expenses -',
      'no_income_yet': 'No income registered yet',
      'expenses_by_category': 'Expenses by Category',
      'of_your_income': 'of your income',
    },
    'pt': {
      'settings_title': 'Configurações ⚙️',
      'settings_subtitle': 'Personalize sua experiência',
      'edit_profile': 'Editar Perfil',
      'premium_upgrade': 'Atualizar para Premium',
      'premium_desc': 'Desbloqueie todos os recursos: sem anúncios, relatórios avançados, sincronização em nuvem e mais.',
      'see_plans': 'Ver Planos',
      'general': 'Geral',
      'notifications': 'Notificações',
      'notifications_desc': 'Alertas e lembretes',
      'language': 'Idioma',
      'dark_theme': 'Tema Escuro',
      'dark_theme_desc': 'Ativar modo noturno',
      'security': 'Segurança',
      'change_password': 'Alterar Senha',
      'change_password_desc': 'Última atualização há 3 meses',
      'two_factor': 'Autenticação em Dois Fatores',
      'two_factor_desc': 'Proteja sua conta',
      'budgets': 'Orçamentos',
      'category_budget': 'Orçamento por Categoria',
      'category_budget_desc': 'Definir limites por categoria',
      'budget_alerts': 'Alertas de Orçamento',
      'budget_alerts_desc': 'Notificações ao se aproximar do limite',
      'appearance': 'Aparência',
      'color_palette': 'Paleta de Cores',
      'color_palette_desc': 'Personalize suas cores',
      'data': 'Dados',
      'cloud_sync': 'Sincronização em Nuvem',
      'cloud_sync_desc': 'Premium',
      'local_backup': 'Backup Local',
      'local_backup_desc': 'Último backup: Hoje',
      'export_data': 'Exportar Dados',
      'export_data_desc': 'Baixar em formato CSV',
      'logout': 'Sair',
      'currency': 'Moeda',
      'currency_desc': 'Selecione sua moeda local',
      'dashboard': 'Painel',
      'transactions': 'Transações',
      'expenses': 'Despesas',
      'total_balance': 'Saldo Total',
      'income': 'Receitas',
      'total_expenses': 'Despesas Totais',
      'recent_transactions': 'Transações Recentes',
      'see_all': 'Ver todas',
      'select_language': 'Selecionar Idioma',
      'select_language_desc': 'Escolha o idioma do aplicativo',
      'select_currency': 'Selecionar Moeda',
      'select_currency_desc': 'Escolha a moeda do aplicativo',
      'select_country': 'Selecionar País',
      'select_country_desc': 'Escolha seu país de residência',
      
      'complete_profile': 'Complete seu perfil!',
      'complete_profile_desc': 'Precisamos de alguns dados para personalizar sua experiência e ajudá-lo a economizar:',
      'country': 'País',
      'salary': 'Salário',
      'complete_now': 'Completar Agora',
      'fixed_expense': 'Despesa Fixa',
      'new_expense': 'Nova Despesa',
      'amount': 'Valor',
      'category': 'Categoria',
      'description_optional': 'Descrição (Opcional)',
      'date': 'Data',
      'add_expense': 'Adicionar Despesa',
      'add_fixed_expense': 'Adicionar Despesa Fixa',
      'expense_added': 'Despesa adicionada com sucesso',
      'fixed_income': 'Renda Fixa',
      'new_income': 'Nova Renda',
      'add_income': 'Adicionar Renda',
      'income_added': 'Renda adicionada com sucesso',
      'new_debt': 'Nova Dívida/Parcela',
      'total_installments': 'Parcelas Totais',
      'paid_installments': 'Parcelas Pagas',
      'add_debt': 'Adicionar Dívida',
      'debt_added': 'Dívida adicionada com sucesso',
      'home': 'Início',
      'debts': 'Dívidas',
      'savings': 'Economias',
      'profile': 'Perfil',
      'welcome_back': 'Bem-vindo de volta,',
      'your_finances': 'Aqui está o seu resumo financeiro',
      'add_first_expense': 'Adicione sua primeira despesa',
      'add_first_debt': 'Adicione sua primeira dívida',
      'save': 'Salvar',
      'cancel': 'Cancelar',
      'save_changes': 'Salvar Alterações',
      'careful': 'Cuidado! ',
      'limit_reached': 'Você atingiu ',
      'limit_monthly': '% do seu limite mensal.',
      'unlocked_badges': 'Distintivos Desbloqueados',
      'quick_actions': 'Ações Rápidas',
      'income_action': 'Renda',
      'expense_action': 'Despesa',
      'ai_assistant': 'Assistente IA',
      'on_track': 'Incrível! Você está em uma sequência 🔥',
      'my_expenses': 'Minhas Despesas 💸',
      'my_incomes': 'Meus Rendimentos 💰',
      'my_debts': 'Minhas Dívidas 💳',
      'my_savings': 'Meus Poupanças 🎯',
      'search_expenses': 'Buscar despesas...',
      'total_expenses_month': 'Total de Despesas -',
      'no_income_yet': 'Nenhuma renda registrada ainda',
      'expenses_by_category': 'Despesas por Categoria',
      'of_your_income': 'da sua renda',
    },
    'fr': {
      'settings_title': 'Paramètres ⚙️',
      'settings_subtitle': 'Personnalisez votre expérience',
      'edit_profile': 'Modifier le Profil',
      'premium_upgrade': 'Passer à Premium',
      'premium_desc': 'Débloquez toutes les fonctionnalités : sans publicité, rapports avancés, synchronisation dans le cloud, etc.',
      'see_plans': 'Voir les Forfaits',
      'general': 'Général',
      'notifications': 'Notifications',
      'notifications_desc': 'Alertes et rappels',
      'language': 'Langue',
      'dark_theme': 'Thème Sombre',
      'dark_theme_desc': 'Activer le mode nuit',
      'security': 'Sécurité',
      'change_password': 'Changer le Mot de Passe',
      'change_password_desc': 'Dernière mise à jour il y a 3 mois',
      'two_factor': 'Authentification à Deux Facteurs',
      'two_factor_desc': 'Protégez votre compte',
      'budgets': 'Budgets',
      'category_budget': 'Budget par Catégorie',
      'category_budget_desc': 'Fixer des limites par catégorie',
      'budget_alerts': 'Alertes de Budget',
      'budget_alerts_desc': 'Notifications à l\'approche de la limite',
      'appearance': 'Apparence',
      'color_palette': 'Palette de Couleurs',
      'color_palette_desc': 'Personnalisez vos couleurs',
      'data': 'Données',
      'cloud_sync': 'Synchronisation Cloud',
      'cloud_sync_desc': 'Premium',
      'local_backup': 'Sauvegarde Locale',
      'local_backup_desc': 'Dernière sauvegarde : Aujourd\'hui',
      'export_data': 'Exporter les Données',
      'export_data_desc': 'Télécharger au format CSV',
      'logout': 'Déconnexion',
      'currency': 'Devise',
      'currency_desc': 'Sélectionnez votre devise locale',
      'dashboard': 'Tableau de Bord',
      'transactions': 'Transactions',
      'expenses': 'Dépenses',
      'total_balance': 'Solde Total',
      'income': 'Revenus',
      'total_expenses': 'Dépenses Totales',
      'recent_transactions': 'Transactions Récentes',
      'see_all': 'Voir tout',
      'select_language': 'Choisir la Langue',
      'select_language_desc': 'Choisissez la langue de l\'application',
      'select_currency': 'Choisir la Devise',
      'select_currency_desc': 'Choisissez la devise de l\'application',
      'select_country': 'Choisir le Pays',
      'select_country_desc': 'Choisissez votre pays de résidence',
      
      'complete_profile': 'Complétez votre profil !',
      'complete_profile_desc': 'Nous avons besoin de quelques données pour personnaliser votre expérience et vous aider à économiser :',
      'country': 'Pays',
      'salary': 'Salaire',
      'complete_now': 'Compléter Maintenant',
      'fixed_expense': 'Dépense Fixe',
      'new_expense': 'Nouvelle Dépense',
      'amount': 'Montant',
      'category': 'Catégorie',
      'description_optional': 'Description (Optionnel)',
      'date': 'Date',
      'add_expense': 'Ajouter une Dépense',
      'add_fixed_expense': 'Ajouter Dépense Fixe',
      'expense_added': 'Dépense ajoutée avec succès',
      'fixed_income': 'Revenu Fixe',
      'new_income': 'Nouveau Revenu',
      'add_income': 'Ajouter un Revenu',
      'income_added': 'Revenu ajouté avec succès',
      'new_debt': 'Nouvelle Dette/Mensualité',
      'total_installments': 'Mensualités Totales',
      'paid_installments': 'Mensualités Payées',
      'add_debt': 'Ajouter une Dette',
      'debt_added': 'Dette ajoutée avec succès',
      'home': 'Accueil',
      'debts': 'Dettes',
      'savings': 'Économies',
      'profile': 'Profil',
      'welcome_back': 'Bon retour,',
      'your_finances': 'Voici votre résumé financier',
      'add_first_expense': 'Ajoutez votre première dépense',
      'add_first_debt': 'Ajoutez votre première dette',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'save_changes': 'Enregistrer les Modifications',
      'careful': 'Attention ! ',
      'limit_reached': 'Vous avez atteint ',
      'limit_monthly': '% de votre limite mensuelle.',
      'unlocked_badges': 'Badges Débloqués',
      'quick_actions': 'Actions Rapides',
      'income_action': 'Revenu',
      'expense_action': 'Dépense',
      'ai_assistant': 'Assistant IA',
      'on_track': 'Incroyable ! Vous êtes sur une lancée 🔥',
      'my_expenses': 'Mes Dépenses 💸',
      'my_incomes': 'Mes Revenus 💰',
      'my_debts': 'Mes Dettes 💳',
      'my_savings': 'Mes Épargnes 🎯',
      'search_expenses': 'Rechercher des dépenses...',
      'total_expenses_month': 'Total des Dépenses -',
      'no_income_yet': 'Aucun revenu enregistré pour le moment',
      'expenses_by_category': 'Dépenses par Catégorie',
      'of_your_income': 'de vos revenus',
    },
    'it': {
      'settings_title': 'Impostazioni ⚙️',
      'settings_subtitle': 'Personalizza la tua esperienza',
      'edit_profile': 'Modifica Profilo',
      'premium_upgrade': 'Passa a Premium',
      'premium_desc': 'Sblocca tutte le funzioni: senza pubblicità, report avanzati, sincronizzazione cloud e altro.',
      'see_plans': 'Vedi Piani',
      'general': 'Generale',
      'notifications': 'Notifiche',
      'notifications_desc': 'Avvisi e promemoria',
      'language': 'Lingua',
      'dark_theme': 'Tema Scuro',
      'dark_theme_desc': 'Abilita modalità notte',
      'security': 'Sicurezza',
      'change_password': 'Cambia Password',
      'change_password_desc': 'Ultimo aggiornamento 3 mesi fa',
      'two_factor': 'Autenticazione a Due Fattori',
      'two_factor_desc': 'Proteggi il tuo account',
      'budgets': 'Budget',
      'category_budget': 'Budget per Categoria',
      'category_budget_desc': 'Imposta limiti per categoria',
      'budget_alerts': 'Avvisi di Budget',
      'budget_alerts_desc': 'Notifiche quando ti avvicini al limite',
      'appearance': 'Aspetto',
      'color_palette': 'Tavolozza Colori',
      'color_palette_desc': 'Personalizza i tuoi colori',
      'data': 'Dati',
      'cloud_sync': 'Sincronizzazione Cloud',
      'cloud_sync_desc': 'Premium',
      'local_backup': 'Backup Locale',
      'local_backup_desc': 'Ultimo backup: Oggi',
      'export_data': 'Esporta Dati',
      'export_data_desc': 'Scarica in formato CSV',
      'logout': 'Disconnettersi',
      'currency': 'Valuta',
      'currency_desc': 'Seleziona la tua valuta locale',
      'dashboard': 'Pannello',
      'transactions': 'Transazioni',
      'expenses': 'Spese',
      'total_balance': 'Saldo Totale',
      'income': 'Reddito',
      'total_expenses': 'Spese Totali',
      'recent_transactions': 'Transazioni Recenti',
      'see_all': 'Vedi tutto',
      'select_language': 'Seleziona Lingua',
      'select_language_desc': 'Scegli la lingua dell\'applicazione',
      'select_currency': 'Seleziona Valuta',
      'select_currency_desc': 'Scegli la valuta dell\'applicazione',
      'select_country': 'Seleziona Paese',
      'select_country_desc': 'Scegli il tuo paese di residenza',
      
      'complete_profile': 'Completa il tuo profilo!',
      'complete_profile_desc': 'Abbiamo bisogno di alcuni dati per personalizzare la tua esperienza e aiutarti a risparmiare:',
      'country': 'Paese',
      'salary': 'Stipendio',
      'complete_now': 'Completa Ora',
      'fixed_expense': 'Spesa Fissa',
      'new_expense': 'Nuova Spesa',
      'amount': 'Importo',
      'category': 'Categoria',
      'description_optional': 'Descrizione (Opzionale)',
      'date': 'Data',
      'add_expense': 'Aggiungi Spesa',
      'add_fixed_expense': 'Aggiungi Spesa Fissa',
      'expense_added': 'Spesa aggiunta con successo',
      'fixed_income': 'Reddito Fisso',
      'new_income': 'Nuovo Reddito',
      'add_income': 'Aggiungi Reddito',
      'income_added': 'Reddito aggiunto con successo',
      'new_debt': 'Nuovo Debito/Rata',
      'total_installments': 'Rate Totali',
      'paid_installments': 'Rate Pagate',
      'add_debt': 'Aggiungi Debito',
      'debt_added': 'Debito aggiunto con successo',
      'home': 'Home',
      'debts': 'Debiti',
      'savings': 'Risparmi',
      'profile': 'Profilo',
      'welcome_back': 'Bentornato,',
      'your_finances': 'Ecco il tuo riepilogo finanziario',
      'add_first_expense': 'Aggiungi la tua prima spesa',
      'add_first_debt': 'Aggiungi il tuo primo debito',
      'save': 'Salva',
      'cancel': 'Annulla',
      'save_changes': 'Salva Modifiche',
      'careful': 'Attenzione! ',
      'limit_reached': 'Hai raggiunto il ',
      'limit_monthly': '% del tuo limite mensile.',
      'unlocked_badges': 'Distintivi Sbloccati',
      'quick_actions': 'Azioni Rapide',
      'income_action': 'Reddito',
      'expense_action': 'Spesa',
      'ai_assistant': 'Assistente IA',
      'on_track': 'Incredibile! Sei in una striscia 🔥',
      'my_expenses': 'Le Mie Spese 💸',
      'my_incomes': 'I Miei Redditi 💰',
      'my_debts': 'I Miei Debiti 💳',
      'my_savings': 'I Miei Risparmi 🎯',
      'search_expenses': 'Cerca spese...',
      'total_expenses_month': 'Totale Spese -',
      'no_income_yet': 'Nessun reddito registrato ancora',
      'expenses_by_category': 'Spese per Categoria',
      'of_your_income': 'del tuo reddito',
    }
  };

  String get(String key) {
    String mappedCode = intlLocale;
    final val = _localizedValues[mappedCode]?[key] ?? _localizedValues['es']?[key];
    if (val != null) return val;
    return _fallbackTranslate(key, mappedCode);
  }

  String translateCategory(String code) {
    if (code.runes.isNotEmpty && code.runes.first > 127 && code.length <= 4) return code;
    final clean = code.toLowerCase().trim();
    String mappedCode = intlLocale;

    final mapEs = {
      'food': 'Comida',
      'food_grocery': 'Supermercado',
      'food_restaurant': 'Restaurante',
      'food_coffee': 'Cafetería',
      'food_delivery': 'Delivery',
      'transport': 'Transporte',
      'transport_gas': 'Gasolina',
      'transport_public': 'Transporte Público',
      'transport_taxi': 'Taxi / App',
      'transport_flight': 'Vuelos',
      'bills': 'Servicios',
      'bills_water': 'Agua',
      'bills_electricity': 'Luz',
      'bills_internet': 'Internet / TV',
      'bills_gas': 'Gas',
      'shopping': 'Compras',
      'shopping_clothes': 'Ropa y Calzado',
      'shopping_electronics': 'Electrónica',
      'shopping_gifts': 'Regalos',
      'entertainment': 'Entretenimiento',
      'entertainment_movies': 'Cine',
      'entertainment_music': 'Música',
      'entertainment_sports': 'Deportes',
      'entertainment_subscriptions': 'Suscripciones',
      'health': 'Salud',
      'health_doctor': 'Médico',
      'health_pharmacy': 'Farmacia',
      'health_gym': 'Gimnasio',
      'home': 'Hogar',
      'home_rent': 'Alquiler / Hipoteca',
      'home_maintenance': 'Mantenimiento',
      'home_furniture': 'Muebles',
      'education': 'Educación',
      'education_tuition': 'Colegiatura',
      'education_books': 'Libros / Material',
      'education_courses': 'Cursos',
      'other': 'Otros',
      'salary': 'Salario',
      'freelance': 'Freelance',
      'investments': 'Inversiones',
      'business': 'Negocio',
      'gifts': 'Regalos',
      'car': 'Carro / Vehículo',
      'rent': 'Alquiler de casa',
      'alquiler de casa': 'Alquiler de casa',
      'credit_card': 'Tarjeta de Crédito',
      'subscription': 'Suscripción',
      'loan': 'Préstamo',
    };

    final mapEn = {
      'food': 'Food',
      'food_grocery': 'Groceries',
      'food_restaurant': 'Restaurant',
      'food_coffee': 'Coffee Shop',
      'food_delivery': 'Delivery',
      'transport': 'Transport',
      'transport_gas': 'Gasoline',
      'transport_public': 'Public Transport',
      'transport_taxi': 'Taxi / App',
      'transport_flight': 'Flights',
      'bills': 'Bills & Utilities',
      'bills_water': 'Water',
      'bills_electricity': 'Electricity',
      'bills_internet': 'Internet / TV',
      'bills_gas': 'Gas',
      'shopping': 'Shopping',
      'shopping_clothes': 'Clothes & Shoes',
      'shopping_electronics': 'Electronics',
      'shopping_gifts': 'Gifts',
      'entertainment': 'Entertainment',
      'entertainment_movies': 'Movies',
      'entertainment_music': 'Music',
      'entertainment_sports': 'Sports',
      'entertainment_subscriptions': 'Subscriptions',
      'health': 'Health',
      'health_doctor': 'Doctor',
      'health_pharmacy': 'Pharmacy',
      'health_gym': 'Gym',
      'home': 'Home',
      'home_rent': 'Rent / Mortgage',
      'home_maintenance': 'Maintenance',
      'home_furniture': 'Furniture',
      'education': 'Education',
      'education_tuition': 'Tuition',
      'education_books': 'Books / Supplies',
      'education_courses': 'Courses',
      'other': 'Other',
      'salary': 'Salary',
      'freelance': 'Freelance',
      'investments': 'Investments',
      'business': 'Business',
      'gifts': 'Gifts',
      'car': 'Car / Vehicle',
      'rent': 'House Rent',
      'alquiler de casa': 'House Rent',
      'credit_card': 'Credit Card',
      'subscription': 'Subscription',
      'loan': 'Loan',
    };

    final mapPt = {
      'food': 'Alimentação',
      'food_grocery': 'Supermercado',
      'food_restaurant': 'Restaurante',
      'food_coffee': 'Cafeteria',
      'food_delivery': 'Delivery',
      'transport': 'Transporte',
      'transport_gas': 'Gasolina',
      'transport_public': 'Transporte Público',
      'transport_taxi': 'Táxi / App',
      'transport_flight': 'Voos',
      'bills': 'Contas e Serviços',
      'bills_water': 'Água',
      'bills_electricity': 'Luz',
      'bills_internet': 'Internet / TV',
      'bills_gas': 'Gás',
      'shopping': 'Compras',
      'shopping_clothes': 'Roupas e Calçados',
      'shopping_electronics': 'Eletrônicos',
      'shopping_gifts': 'Presentes',
      'entertainment': 'Entretenimento',
      'entertainment_movies': 'Cinema',
      'entertainment_music': 'Música',
      'entertainment_sports': 'Esportes',
      'entertainment_subscriptions': 'Assinaturas',
      'health': 'Saúde',
      'health_doctor': 'Médico',
      'health_pharmacy': 'Farmácia',
      'health_gym': 'Academia',
      'home': 'Casa',
      'home_rent': 'Aluguel / Hipoteca',
      'home_maintenance': 'Manutenção',
      'home_furniture': 'Móveis',
      'education': 'Educação',
      'education_tuition': 'Mensalidade',
      'education_books': 'Livros / Materiais',
      'education_courses': 'Cursos',
      'other': 'Outros',
      'salary': 'Salário',
      'freelance': 'Freelance',
      'investments': 'Investimentos',
      'business': 'Negócios',
      'gifts': 'Presentes',
      'car': 'Carro / Veículo',
      'rent': 'Aluguel de casa',
      'alquiler de casa': 'Aluguel de casa',
      'credit_card': 'Cartão de Crédito',
      'subscription': 'Assinatura',
      'loan': 'Empréstimo',
    };

    final mapFr = {
      'food': 'Nourriture',
      'food_grocery': 'Supermarché',
      'food_restaurant': 'Restaurant',
      'food_coffee': 'Café',
      'food_delivery': 'Livraison',
      'transport': 'Transport',
      'transport_gas': 'Essence',
      'transport_public': 'Transport en commun',
      'transport_taxi': 'Taxi / App',
      'transport_flight': 'Vols',
      'bills': 'Factures et Services',
      'bills_water': 'Eau',
      'bills_electricity': 'Électricité',
      'bills_internet': 'Internet / TV',
      'bills_gas': 'Gaz',
      'shopping': 'Achats',
      'shopping_clothes': 'Vêtements',
      'shopping_electronics': 'Électronique',
      'shopping_gifts': 'Cadeaux',
      'entertainment': 'Divertissement',
      'entertainment_movies': 'Cinéma',
      'entertainment_music': 'Musique',
      'entertainment_sports': 'Sports',
      'entertainment_subscriptions': 'Abonnements',
      'health': 'Santé',
      'health_doctor': 'Médecin',
      'health_pharmacy': 'Pharmacie',
      'health_gym': 'Salle de sport',
      'home': 'Maison',
      'home_rent': 'Loyer / Hypothèque',
      'home_maintenance': 'Entretien',
      'home_furniture': 'Meubles',
      'education': 'Éducation',
      'education_tuition': 'Scolarité',
      'education_books': 'Livres / Fournitures',
      'education_courses': 'Cours',
      'other': 'Autres',
      'salary': 'Salaire',
      'freelance': 'Freelance',
      'investments': 'Investissements',
      'business': 'Affaires',
      'gifts': 'Cadeaux',
      'car': 'Voiture',
      'rent': 'Loyer',
      'alquiler de casa': 'Loyer',
      'credit_card': 'Carte de Crédit',
      'subscription': 'Abonnement',
      'loan': 'Prêt',
    };

    final mapIt = {
      'food': 'Cibo',
      'food_grocery': 'Supermercato',
      'food_restaurant': 'Ristorante',
      'food_coffee': 'Caffetteria',
      'food_delivery': 'Consegna',
      'transport': 'Trasporti',
      'transport_gas': 'Benzina',
      'transport_public': 'Trasporto Pubblico',
      'transport_taxi': 'Taxi / App',
      'transport_flight': 'Voli',
      'bills': 'Bollette e Servizi',
      'bills_water': 'Acqua',
      'bills_electricity': 'Luce',
      'bills_internet': 'Internet / TV',
      'bills_gas': 'Gas',
      'shopping': 'Acquisti',
      'shopping_clothes': 'Abbigliamento',
      'shopping_electronics': 'Elettronica',
      'shopping_gifts': 'Regali',
      'entertainment': 'Intrattenimento',
      'entertainment_movies': 'Cinema',
      'entertainment_music': 'Musica',
      'entertainment_sports': 'Sport',
      'entertainment_subscriptions': 'Abbonamenti',
      'health': 'Salute',
      'health_doctor': 'Medico',
      'health_pharmacy': 'Farmacia',
      'health_gym': 'Palestra',
      'home': 'Casa',
      'home_rent': 'Affitto / Mutuo',
      'home_maintenance': 'Manutenzione',
      'home_furniture': 'Mobili',
      'education': 'Istruzione',
      'education_tuition': 'Retta Scolastica',
      'education_books': 'Libri / Materiali',
      'education_courses': 'Corsi',
      'other': 'Altri',
      'salary': 'Stipendio',
      'freelance': 'Freelance',
      'investments': 'Investimenti',
      'business': 'Affari',
      'gifts': 'Regali',
      'car': 'Auto / Veicolo',
      'rent': 'Affitto casa',
      'alquiler de casa': 'Affitto casa',
      'credit_card': 'Carta di Credito',
      'subscription': 'Abbonamento',
      'loan': 'Prestito',
    };

    if (mappedCode == 'en') return mapEn[clean] ?? mapEs[clean] ?? code;
    if (mappedCode == 'pt') return mapPt[clean] ?? mapEs[clean] ?? code;
    if (mappedCode == 'fr') return mapFr[clean] ?? mapEs[clean] ?? code;
    if (mappedCode == 'it') return mapIt[clean] ?? mapEs[clean] ?? code;
    return mapEs[clean] ?? code;
  }

  String _fallbackTranslate(String key, String mappedCode) {
    final clean = key.toLowerCase().trim();
    final esMap = {
      'history': 'Historial',
      'no_transactions': 'Sin movimientos registrados',
      'frequency': 'Frecuencia',
      'billing_day': 'Día de cobro',
      'understood': 'Entendido',
      'weekly': 'Semanal',
      'bimonthly': 'Quincenal',
      'monthly': 'Mensual',
      'credit_card_history': 'Historial de Tarjeta',
      'credit_cards': 'Tarjetas de Crédito',
      'accounts_cash': 'Cuentas y Efectivo',
      'today_expenses': 'Gastos de hoy',
      'today_income': 'Ingresos de hoy',
      'recent_activity': 'Actividad Reciente',
      'subscriptions': 'Suscripciones y Gastos Fijos',
      'pay': 'Abonar',
      'details': 'Detalles',
      'fixed': 'Fijo',
      'select_category': 'Selecciona Categoría',
    };
    final enMap = {
      'history': 'History',
      'no_transactions': 'No transactions recorded',
      'frequency': 'Frequency',
      'billing_day': 'Billing Day',
      'understood': 'Got it',
      'weekly': 'Weekly',
      'bimonthly': 'Bi-weekly',
      'monthly': 'Monthly',
      'credit_card_history': 'Card History',
      'credit_cards': 'Credit Cards',
      'accounts_cash': 'Accounts & Cash',
      'today_expenses': "Today's Expenses",
      'today_income': "Today's Income",
      'recent_activity': 'Recent Activity',
      'subscriptions': 'Subscriptions & Fixed Expenses',
      'pay': 'Pay',
      'details': 'Details',
      'fixed': 'Fixed',
      'select_category': 'Select Category',
    };
    final ptMap = {
      'history': 'Histórico',
      'no_transactions': 'Sem transações registradas',
      'frequency': 'Frequência',
      'billing_day': 'Dia de cobrança',
      'understood': 'Entendido',
      'weekly': 'Semanal',
      'bimonthly': 'Quinzenal',
      'monthly': 'Mensal',
      'credit_card_history': 'Histórico do Cartão',
      'credit_cards': 'Cartões de Crédito',
      'accounts_cash': 'Contas e Dinheiro',
      'today_expenses': 'Gastos de hoje',
      'today_income': 'Receitas de hoje',
      'recent_activity': 'Atividade Recente',
      'subscriptions': 'Assinaturas e Gastos Fixos',
      'pay': 'Pagar',
      'details': 'Detalhes',
      'fixed': 'Fixo',
      'select_category': 'Selecione a Categoria',
    };
    final frMap = {
      'history': 'Historique',
      'no_transactions': 'Aucune transaction enregistrée',
      'frequency': 'Fréquence',
      'billing_day': 'Jour de facturation',
      'understood': 'Compris',
      'weekly': 'Hebdomadaire',
      'bimonthly': 'Bimensuel',
      'monthly': 'Mensuel',
      'credit_card_history': 'Historique de Carte',
      'credit_cards': 'Cartes de Crédit',
      'accounts_cash': 'Comptes & Espèces',
      'today_expenses': "Dépenses d'aujourd'hui",
      'today_income': "Revenus d'aujourd'hui",
      'recent_activity': 'Activité Récente',
      'subscriptions': 'Abonnements et Frais Fixes',
      'pay': 'Payer',
      'details': 'Détails',
      'fixed': 'Fixe',
      'select_category': 'Sélectionner la catégorie',
    };
    final itMap = {
      'history': 'Cronologia',
      'no_transactions': 'Nessuna transazione registrata',
      'frequency': 'Frequenza',
      'billing_day': 'Giorno di addebito',
      'understood': 'Capito',
      'weekly': 'Settimanale',
      'bimonthly': 'Quindicinale',
      'monthly': 'Mensile',
      'credit_card_history': 'Cronologia Carta',
      'credit_cards': 'Carte di Credito',
      'accounts_cash': 'Conti e Contanti',
      'today_expenses': 'Spese di oggi',
      'today_income': 'Entrate di oggi',
      'recent_activity': 'Attività Recente',
      'subscriptions': 'Abbonamenti e Spese Fisse',
      'pay': 'Pagare',
      'details': 'Dettagli',
      'fixed': 'Fisso',
      'select_category': 'Seleziona Categoria',
    };

    if (mappedCode == 'en') return enMap[clean] ?? esMap[clean] ?? key;
    if (mappedCode == 'pt') return ptMap[clean] ?? esMap[clean] ?? key;
    if (mappedCode == 'fr') return frMap[clean] ?? esMap[clean] ?? key;
    if (mappedCode == 'it') return itMap[clean] ?? esMap[clean] ?? key;
    return esMap[clean] ?? key;
  }
}
