// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf3pJQ-3Cb34ZkQkRkMtkOgES4o3hOVME',
    appId: '1:164540827567:web:9a0adb61d01092f886915a',
    messagingSenderId: '164540827567',
    projectId: 'zentai-9b38a',
    authDomain: 'zentai-9b38a.firebaseapp.com',
    storageBucket: 'zentai-9b38a.firebasestorage.app',
    measurementId: 'G-01JBHFY4KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMtI8eoEC8e3kMn_c4Vh5IfYVT6zrU7DA',
    appId: '1:164540827567:android:ad037635c866960386915a',
    messagingSenderId: '164540827567',
    projectId: 'zentai-9b38a',
    storageBucket: 'zentai-9b38a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWuvySRWtQ9uABcQirt5OzjKC5P-pL7og',
    appId: '1:164540827567:ios:16a63f40b785d9ab86915a',
    messagingSenderId: '164540827567',
    projectId: 'zentai-9b38a',
    storageBucket: 'zentai-9b38a.firebasestorage.app',
    iosBundleId: 'com.marro.appfinanciera.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWuvySRWtQ9uABcQirt5OzjKC5P-pL7og',
    appId: '1:164540827567:ios:16a63f40b785d9ab86915a',
    messagingSenderId: '164540827567',
    projectId: 'zentai-9b38a',
    storageBucket: 'zentai-9b38a.firebasestorage.app',
    iosBundleId: 'com.marro.appfinanciera.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf3pJQ-3Cb34ZkQkRkMtkOgES4o3hOVME',
    appId: '1:164540827567:web:76fd2e8701906d1786915a',
    messagingSenderId: '164540827567',
    projectId: 'zentai-9b38a',
    authDomain: 'zentai-9b38a.firebaseapp.com',
    storageBucket: 'zentai-9b38a.firebasestorage.app',
    measurementId: 'G-D6W9DSYPKB',
  );
}
